import Link from 'next/link';
import { requireSession } from '../../lib/auth';
import { loadReferenceLab } from '../../lib/reference-lab';

export const dynamic = 'force-dynamic';
const compact = (value: unknown) => new Intl.NumberFormat('en-US', { notation: 'compact', maximumFractionDigits: 1 }).format(Number(value || 0));
const date = (value: unknown) => value ? new Intl.DateTimeFormat('en-GB', { dateStyle: 'medium' }).format(new Date(String(value))) : '—';
const sortLabel = (value: string) => ({ outlier: 'outlier', views: 'views', views_day: 'views/day', date: 'date' }[value] ?? 'outlier');

export default async function ReferenceLab({ searchParams }: { searchParams: Promise<{ sort?: string; format?: string; channel?: string }> }) {
  await requireSession();
  const params = await searchParams;
  const data = await loadReferenceLab({ sort: params.sort, format: params.format, channelId: params.channel });
  const makeHref = (values: Record<string, string | undefined>) => { const next = new URLSearchParams(); const merged = { sort: data.sort, format: data.format, channel: data.selectedChannel ?? undefined, ...values }; for (const [key, value] of Object.entries(merged)) if (value && value !== 'ALL') next.set(key, value); return `/reference-lab?${next.toString()}`; };
  return <div className="content"><header className="topbar"><div><p className="eyebrow">Benchmark-first</p><h1>Reference Lab</h1><p className="muted">Ganadores observables, patrones transferibles y packs de referencia.</p></div><Link className="pill info" href="/">← Portfolio</Link></header><main className="main">
    <section className="section card"><div className="section-head"><div><p className="eyebrow">Seed channels</p><h2>Canales de referencia</h2></div><span className="fine">Los seeds son puntos de partida; las estadísticas se revalidan por API.</span></div><div className="cards">{data.channels.length ? data.channels.map((channel: any) => <Link className="card" href={makeHref({ channel: String(channel.id) })} key={channel.id}><div className="row"><h3>{channel.title}</h3><span className="pill info">{Number(channel.strongest_outlier || 0).toFixed(0)} outlier</span></div><div className="meta">{channel.handle || channel.youtube_channel_id || 'sin handle'} · {channel.niche || 'niche pendiente'}</div><div className="kpis"><div className="kpi"><span>Subscribers</span><strong>{compact(channel.subscribers)}</strong></div><div className="kpi"><span>Total views</span><strong>{compact(channel.total_views)}</strong></div><div className="kpi"><span>Videos</span><strong>{compact(channel.total_videos)}</strong></div></div></Link>) : <div className="empty">No hay canales competidores sincronizados todavía. Ejecuta el market cycle con credenciales o usa el benchmark smoke test.</div>}</div></section>
    <section className="section card"><div className="section-head"><div><p className="eyebrow">Reference pack inputs</p><h2>Vídeos observados</h2></div><div className="row"><Link className={`pill ${data.format === 'ALL' ? 'good' : 'info'}`} href={makeHref({ format: 'ALL' })}>Todos</Link><Link className={`pill ${data.format === 'LONG_FORM' ? 'good' : 'info'}`} href={makeHref({ format: 'LONG_FORM' })}>Long-form</Link><Link className={`pill ${data.format === 'SHORTS' ? 'good' : 'info'}`} href={makeHref({ format: 'SHORTS' })}>Shorts</Link></div></div><div className="row" style={{ marginBottom: 14 }}><span className="fine">Orden actual: {sortLabel(data.sort)}</span><Link className="pill info" href={makeHref({ sort: 'outlier' })}>Outlier</Link><Link className="pill info" href={makeHref({ sort: 'views' })}>Views</Link><Link className="pill info" href={makeHref({ sort: 'views_day' })}>Views/day</Link><Link className="pill info" href={makeHref({ sort: 'date' })}>Fecha</Link></div><div className="table-wrap"><table><thead><tr><th>Vídeo</th><th>Publicado</th><th>Duración</th><th>Views</th><th>Views/day</th><th>Outlier</th><th>Uso</th></tr></thead><tbody>{data.videos.length ? data.videos.map((video: any) => <tr key={video.id}><td><strong>{video.title}</strong><div className="fine">{video.youtube_video_id}</div></td><td>{date(video.published_at)}</td><td>{video.duration_seconds ? `${Math.round(Number(video.duration_seconds) / 60)}m` : '—'}</td><td>{compact(video.views)}</td><td>{compact(video.views_per_day)}</td><td><span className={`pill ${Number(video.outlier_score) >= 78 ? 'good' : 'info'}`}>{Number(video.outlier_score || 0).toFixed(1)}</span></td><td><span className="fine">seleccionable en Reference Pack</span></td></tr>) : <tr><td colSpan={7} className="empty">No hay vídeos para este filtro.</td></tr>}</tbody></table></div></section>
    <section className="section split"><div className="card"><p className="eyebrow">Evidence rule</p><h2>Cómo se usa</h2><p className="muted">Una oportunidad no toma un único vídeo como receta. El pack mezcla framing, title grammar, thumbnail composition, hook, pacing y visual language de 3–7 piezas.</p></div><div className="card"><p className="eyebrow">Guardrail</p><h2>Inspiración ≠ copia</h2><p className="muted">Las referencias aportan estructura y patrones. Scripts, frases distintivas, assets, secuencias y miniaturas completas permanecen fuera del pipeline original.</p></div></section>
  </main></div>;
}
