'use client';

import Link from 'next/link';
import { useState, type FormEvent } from 'react';

type Analysis = { source: { url: string; youtubeVideoId: string }; metadata: { title: string; channelTitle?: string; thumbnailUrl?: string; durationSeconds?: number; views?: number; likes?: number; comments?: number }; titleDNA: { grammar: string; wordCount: number; curiositySignals: string[]; hookHypothesis: string }; availability: Record<string, boolean>; limitations: string[]; safeUse: string; confidence: number };

export default function ReferenceAnalyzerClient() {
  const [url, setUrl] = useState(''); const [analysis, setAnalysis] = useState<Analysis | null>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  async function analyze(event: FormEvent) { event.preventDefault(); setBusy(true); setError(''); setAnalysis(null); try { const response = await fetch('/api/reference-analysis', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ url }) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error || 'No se pudo analizar el vídeo.'); setAnalysis(payload.analysis); } catch (reason) { setError(reason instanceof Error ? reason.message : String(reason)); } finally { setBusy(false); } }
  const prompt = analysis ? `Crea un vídeo original inspirado en la estructura de «${analysis.metadata.title}»: conserva su familia de hook (${analysis.titleDNA.grammar}), pero cambia completamente el tema, guion, escenas, recursos, audio y diseño. ${analysis.titleDNA.hookHypothesis}` : '';
  return <div className="content"><header className="topbar"><div><p className="eyebrow">Reference intelligence</p><h1>Analizar vídeo de referencia</h1><p className="muted">Extrae señales verificables de una URL y conviértelas en una dirección creativa original.</p></div><Link className="pill info" href="/reference-lab">← Referencias</Link></header><main className="main"><section className="card reference-analyzer-card"><form onSubmit={analyze} className="reference-analyzer-form"><label>URL pública de YouTube<input value={url} onChange={(event) => setUrl(event.target.value)} placeholder="https://youtu.be/..." required /></label><button className="primary" disabled={busy}>{busy ? 'Analizando…' : 'Analizar vídeo'}</button></form>{error ? <p className="error">{error}</p> : null}<p className="fine">La herramienta no inventa datos: si no hay transcripción, retención o acceso autorizado a recursos, lo indica como no disponible.</p></section>{analysis ? <section className="reference-analysis-grid"><div className="card"><p className="eyebrow">Ficha verificable</p><h2>{analysis.metadata.title}</h2><p className="muted">{analysis.metadata.channelTitle || 'Canal no disponible'} · confianza de metadatos {analysis.confidence}%</p>{analysis.metadata.thumbnailUrl ? <img className="reference-thumbnail" src={analysis.metadata.thumbnailUrl} alt="Miniatura del vídeo analizado" /> : null}<div className="kpis"><div className="kpi"><span>Duración</span><strong>{analysis.metadata.durationSeconds ? `${Math.round(analysis.metadata.durationSeconds / 60)}m` : '—'}</strong></div><div className="kpi"><span>Views públicas</span><strong>{analysis.metadata.views?.toLocaleString() || '—'}</strong></div><div className="kpi"><span>Fuente</span><strong>oEmbed/API</strong></div></div></div><div className="card"><p className="eyebrow">Content DNA disponible</p><h2>Hook y estructura</h2><p><strong>{analysis.titleDNA.grammar}</strong> · {analysis.titleDNA.wordCount} palabras</p><p className="muted">{analysis.titleDNA.hookHypothesis}</p><div className="tag-row">{analysis.titleDNA.curiositySignals.map((signal) => <span className="pill info" key={signal}>{signal}</span>)}</div><h3>Estado de las señales</h3>{Object.entries(analysis.availability).map(([key, value]) => <div className="availability-row" key={key}><span>{key}</span><strong className={value ? 'good-text' : 'muted'}>{value ? 'Disponible' : 'No disponible'}</strong></div>)}<p className="fine">{analysis.safeUse}</p>{analysis.limitations.map((item) => <p className="fine" key={item}>• {item}</p>)}<Link className="primary" href={`/create?prompt=${encodeURIComponent(prompt)}`}>Usar esta estructura como inspiración →</Link></div></section> : null}</main></div>;
}
