import Link from 'next/link';
import { requireSession } from '../lib/auth';
import { loadDashboard } from '../lib/data';
import { LogoutButton } from '../components/logout-button';

export const dynamic='force-dynamic';
const money=(value:unknown)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:2}).format(Number(value||0));
const compact=(value:unknown)=>new Intl.NumberFormat('en-US',{notation:'compact',maximumFractionDigits:1}).format(Number(value||0));
const pct=(value:unknown)=>`${(Number(value||0)*100).toFixed(1)}%`;
const score=(value:unknown)=>Number.isFinite(Number(value))?Math.round(Number(value)):'—';
const stateClass=(state:unknown)=>{const s=String(state||'').toLowerCase();return ['ready','public','scheduled','succeeded','produced'].some((x)=>s.includes(x))?'good':['blocked','dead','failed','rejected'].some((x)=>s.includes(x))?'bad':['retry','awaiting','candidate','private'].some((x)=>s.includes(x))?'warn':'info';};

function Shell({children}:{children:React.ReactNode}){return <div className="app-shell"><aside className="sidebar"><div className="brand"><div className="brand-mark">A</div><div className="brand-copy"><strong>AUTO-YTB</strong><span>Autonomous Channel OS</span></div></div><nav className="nav"><a className="active" href="#overview">Overview</a><a href="#videos">Vídeos</a><a href="#learning">Creative Lab</a><a href="#market">Mercado</a></nav><div className="sidebar-footer"><LogoutButton/></div></aside><div className="content">{children}<nav className="mobile-nav"><a href="#overview">Inicio</a><a href="#videos">Vídeos</a><a href="#learning">Lab</a><a href="#market">Mercado</a></nav></div></div>}

export default async function Home(){
  await requireSession();const data=await loadDashboard();
  const queue=Object.fromEntries(data.jobs.map((row)=>[String(row.state),Number(row.count||0)]));
  const pipeline=['Market','Opportunity','Channel','Research','Script','Voice','Visuals','QA','Publish'];
  return <Shell><header className="topbar"><div><p className="eyebrow">Portfolio</p><h1>Autonomous Channel OS</h1></div><span className="pill good"><span className="status-dot"/>Online</span></header><main className="main" id="overview">
    <section className="metric-grid">
      <div className="metric"><div className="label">Profit</div><div className="value">{money(data.portfolio.profit)}</div><div className="sub">Revenue {money(data.portfolio.revenue)}</div></div>
      <div className="metric"><div className="label">Coste</div><div className="value">{money(data.portfolio.cost)}</div><div className="sub">Ledger reconciliado</div></div>
      <div className="metric"><div className="label">ROI</div><div className="value">{data.portfolio.roi==null?'—':`${data.portfolio.roi.toFixed(2)}x`}</div><div className="sub">Profit / coste</div></div>
      <div className="metric"><div className="label">Views</div><div className="value">{compact(data.portfolio.views)}</div><div className="sub">Último snapshot/video</div></div>
      <div className="metric"><div className="label">Watch time</div><div className="value">{compact(data.portfolio.watchMinutes)}m</div><div className="sub">Minutos vistos</div></div>
      <div className="metric"><div className="label">Canales</div><div className="value">{data.portfolio.channels}</div><div className="sub">{data.portfolio.candidates} candidatos</div></div>
    </section>

    <section className="section"><div className="section-head"><div><p className="eyebrow">Factory</p><h2>Flujo end-to-end</h2></div><span className="fine">Sin clicks requeridos en modo FULL_AUTONOMOUS</span></div><div className="pipeline">{pipeline.map((item,index)=><div className="pipe-step" key={item}><strong>{String(index+1).padStart(2,'0')} · {item}</strong><span>{index===7?'Attention + media + rights':index===8?'Private → policy → public':'Autonomous stage'}</span></div>)}</div></section>

    <section className="section"><div className="section-head"><div><p className="eyebrow">Channels</p><h2>Portfolio de canales</h2></div></div><div className="cards">{data.channels.map((channel:any)=><article className="card" key={channel.id}><div className="row"><div><h3>{channel.title||channel.channel_key}</h3><div className="meta">{channel.language?.toUpperCase()} · {channel.niche}</div></div><span className={`pill ${stateClass(channel.lifecycle_state)}`}>{channel.lifecycle_state||'ready'}</span></div><div className="kpis"><div className="kpi"><span>Coste</span><strong>{money(channel.cost)}</strong></div><div className="kpi"><span>Profit</span><strong>{money(channel.profit)}</strong></div><div className="kpi"><span>ROI</span><strong>{channel.roi==null?'—':`${Number(channel.roi).toFixed(2)}x`}</strong></div></div></article>)}{data.candidates.map((candidate:any)=><article className="card" key={candidate.id}><div className="row"><div><h3>{candidate.proposed_name}</h3><div className="meta">{candidate.language?.toUpperCase()} · {candidate.character_mode}</div></div><span className="pill warn">{candidate.status}</span></div><p className="muted">{candidate.proposed_positioning}</p><div className="kpis"><div className="kpi"><span>Opportunity</span><strong>{score(candidate.opportunity_score)}</strong></div><div className="kpi"><span>Route fit</span><strong>{score(candidate.route_score)}</strong></div><div className="kpi"><span>Character</span><strong>{candidate.character_name||'—'}</strong></div></div></article>)}</div></section>

    <section className="section" id="videos"><div className="section-head"><div><p className="eyebrow">Production</p><h2>Vídeos recientes</h2></div><div className="row"><span className="pill">Queued {queue.queued||0}</span><span className="pill warn">Retry {queue.retry||0}</span><span className="pill bad">Dead {queue.dead||0}</span></div></div><div className="table-wrap"><table><thead><tr><th>Vídeo</th><th>Estado</th><th>QA</th><th>Attention</th><th>Coste</th><th>Revenue</th><th>Profit</th><th>ROI</th></tr></thead><tbody>{data.runs.length?data.runs.map((run:any)=>{const attention=run.qa_report?.attention?.score??run.metadata?.attention?.score;return <tr key={run.id}><td><Link className="run-link" href={`/videos/${run.id}`}>{run.working_title||run.angle||run.id.slice(0,8)}</Link><div className="fine">{run.format||'long'} · opportunity {score(run.opportunity_score)}</div></td><td><span className={`pill ${stateClass(run.publication_state||run.state)}`}>{run.publication_state||run.state}</span></td><td className="score">{score(run.qa_score)}</td><td className="score">{score(attention)}</td><td>{money(run.total_cost_usd)}</td><td>{money(run.total_revenue_usd)}</td><td>{money(run.profit_usd)}</td><td>{run.roi==null?'—':`${Number(run.roi).toFixed(2)}x`}</td></tr>}):<tr><td colSpan={8} className="empty">Aún no hay producciones.</td></tr>}</tbody></table></div></section>

    <section className="section split" id="learning"><div className="card"><div className="section-head"><div><p className="eyebrow">Creative Performance Lab</p><h2>Qué está funcionando</h2></div></div><div className="list">{data.creative.slice(0,12).map((item:any)=><div className="list-item" key={`${item.feature_name}:${item.feature_value}`}><div><strong>{item.feature_name}</strong><div className="fine">{item.feature_value} · n={item.sample_size} · {compact(item.weighted_views)} views</div></div><div style={{textAlign:'right'}}><span className="pill info">conf {pct(item.confidence)}</span><div className="fine">AVP {Number(item.average_video_avp||0).toFixed(1)} · ROI {Number(item.average_roi||0).toFixed(2)}x</div></div></div>)}{!data.creative.length?<div className="empty">El laboratorio empezará a aprender tras acumular Analytics propios.</div>:null}</div></div><div className="card"><div className="section-head"><div><p className="eyebrow">Provider spend</p><h2>Coste por proveedor</h2></div></div><div className="list">{data.providers.map((item:any)=><div className="list-item" key={`${item.provider}:${item.model}`}><div><strong>{item.provider}</strong><div className="fine">{item.model} · {item.events} eventos</div></div><div style={{textAlign:'right'}}><strong>{money(item.spend)}</strong>{Number(item.unpriced)>0?<div className="fine" style={{color:'var(--red)'}}>{item.unpriced} sin tarifa</div>:null}</div></div>)}</div></div></section>

    <section className="section" id="market"><div className="section-head"><div><p className="eyebrow">Market pattern lab</p><h2>Patrones públicos observables</h2></div><span className="fine">Sin inventar CTR, retention o revenue de competidores</span></div><div className="table-wrap"><table><thead><tr><th>Formato</th><th>Característica</th><th>Valor</th><th>Muestra</th><th>Canales</th><th>Velocidad</th><th>Outlier rate</th><th>Confianza</th></tr></thead><tbody>{data.market.length?data.market.slice(0,30).map((item:any)=><tr key={`${item.content_format}:${item.feature_name}:${item.feature_value}`}><td>{item.content_format==='SHORT_VERTICAL'?'Short':'Long'}</td><td>{item.feature_name}</td><td><strong>{item.feature_value}</strong></td><td>{item.sample_size}</td><td>{item.unique_channels}</td><td>{Number(item.average_market_velocity_multiple||0).toFixed(2)}x</td><td>{pct(item.outlier_rate)}</td><td>{pct(item.confidence)}</td></tr>):<tr><td colSpan={8} className="empty">El siguiente market cycle generará patrones.</td></tr>}</tbody></table></div></section>
  </main></Shell>;
}
