import Link from 'next/link';
import { notFound } from 'next/navigation';
import { requireSession } from '../../../lib/auth';
import { query } from '../../../lib/db';

export const dynamic='force-dynamic';
const pretty=(v:unknown)=>JSON.stringify(v??{},null,2);
const compact=(v:unknown)=>new Intl.NumberFormat('en-US',{notation:'compact',maximumFractionDigits:1}).format(Number(v||0));
const money=(v:unknown)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:2}).format(Number(v||0));
const pill=(value:unknown)=>{const s=String(value||'').toLowerCase();return ['active','continue','scale','passed','compiled'].some((x)=>s.includes(x))?'good':['paused','conflict','blocked'].some((x)=>s.includes(x))?'bad':'warn';};

export default async function SeriesDetail({params}:{params:Promise<{id:string}>}){
  await requireSession();const {id}=await params;
  const [seriesRows,characters,styles,episodes,arcs,memory,decisions]=await Promise.all([
    query(`select s.*,c.title as channel_title,c.channel_key,b.id as bible_id,b.version as bible_version,b.bible,b.validation,b.continuity_key as bible_continuity_key,
      ps.views,ps.sample_size,ps.average_view_percentage::float,ps.average_view_duration_seconds::float,ps.share_rate::float,ps.subscribers_per_thousand::float,ps.revenue_usd::float,ps.cost_usd::float,ps.profit_usd::float,ps.roi::float,ps.watch_minutes_per_dollar::float
      from series s join channels c on c.id=s.channel_id join lateral (select * from series_bibles x where x.series_id=s.id and x.status='active' order by version desc limit 1) b on true
      left join lateral (select * from series_performance_snapshots x where x.series_id=s.id order by observed_at desc limit 1) ps on true where s.id=$1`,[id]),
    query(`select character_key,name,role,continuity_key,specification,voice_profile,canonical_reference_uri,status from series_characters where series_id=$1 order by created_at`,[id]),
    query(`select style_key,name,continuity_key,specification,canonical_reference_uri,status from series_styles where series_id=$1 order by created_at`,[id]),
    query(`select se.id,se.episode_key,se.season_number,se.episode_number,se.title,se.premise,se.status,se.continuity_status,se.memory_compiled_at,se.production_run_id,se.continuity_snapshot,
      smc.summary,smc.status as memory_status,smc.conflicts,smc.next_episode_seeds
      from series_episodes se left join series_memory_compilations smc on smc.episode_id=se.id where se.series_id=$1 order by se.season_number desc,se.episode_number desc limit 40`,[id]),
    query(`select arc_key,title,status,summary,state,updated_at from series_story_arcs where series_id=$1 order by case status when 'active' then 0 when 'planned' then 1 else 2 end,updated_at desc`,[id]),
    query(`select memory_type,memory_key,payload,importance::float,canonical,active,created_at from series_episode_memory where series_id=$1 and active=true order by importance desc,created_at desc limit 80`,[id]),
    query(`select decision,confidence::float,score::float,rationale,evidence,observed_at from series_strategy_decisions where series_id=$1 order by observed_at desc limit 12`,[id]),
  ]);
  const s:any=seriesRows[0];if(!s)notFound();const bible:any=s.bible??{};
  return <div className="content"><header className="topbar"><div><p className="eyebrow">Series Bible · v{s.bible_version}</p><h1>{s.title}</h1><div className="meta">{s.channel_title||s.channel_key} · {String(s.language).toUpperCase()}</div></div><div className="row"><Link href="/series" className="pill info">← Series</Link><Link href="/" className="pill">Portfolio</Link></div></header><main className="main">
    <section className="metric-grid"><div className="metric"><div className="label">Episodes</div><div className="value">{episodes.length}</div><div className="sub">Bible v{s.bible_version}</div></div><div className="metric"><div className="label">Views</div><div className="value">{s.views==null?'—':compact(s.views)}</div><div className="sub">Último snapshot</div></div><div className="metric"><div className="label">AVP</div><div className="value">{s.average_view_percentage==null?'—':`${Number(s.average_view_percentage).toFixed(1)}%`}</div></div><div className="metric"><div className="label">Profit</div><div className="value">{s.profit_usd==null?'—':money(s.profit_usd)}</div></div><div className="metric"><div className="label">ROI</div><div className="value">{s.roi==null?'—':`${Number(s.roi).toFixed(2)}x`}</div></div><div className="metric"><div className="label">Audience</div><div className="value" style={{fontSize:18}}>{s.audience_mode==='MADE_FOR_KIDS'?`Kids ${s.target_age_min??'?'}–${s.target_age_max??'?'}`:'General'}</div></div></section>

    <section className="section split"><div className="card"><p className="eyebrow">Canon</p><h2>Premise & rules</h2><p>{bible.premise}</p><div className="list">{(bible.worldRules??[]).slice(0,8).map((rule:string,i:number)=><div className="list-item" key={i}><span>{rule}</span></div>)}</div></div><div className="card"><p className="eyebrow">Episode grammar</p><h2>Structure</h2><div className="list">{(bible.episodeStructure??[]).map((rule:string,i:number)=><div className="list-item" key={i}><strong>{String(i+1).padStart(2,'0')}</strong><span>{rule}</span></div>)}</div></div></section>

    <section className="section"><div className="section-head"><div><p className="eyebrow">Characters</p><h2>Persistent cast</h2></div><span className="fine">Continuity keys are immutable identity anchors</span></div><div className="cards">{characters.map((c:any)=><article className="card" key={c.character_key}><div className="row"><div><h3>{c.name}</h3><div className="meta">{c.role||c.character_key}</div></div><span className={`pill ${pill(c.status)}`}>{c.status}</span></div><div className="fine" style={{marginTop:8}}>continuity: {c.continuity_key}</div><div className="code-box" style={{marginTop:12}}>{pretty(c.specification)}</div></article>)}{!characters.length?<div className="card empty">Esta serie no utiliza personajes persistentes.</div>:null}</div></section>

    <section className="section"><div className="section-head"><div><p className="eyebrow">Visual Bible</p><h2>Style canon</h2></div></div><div className="cards">{styles.map((style:any)=><article className="card" key={style.style_key}><div className="row"><h3>{style.name}</h3><span className={`pill ${pill(style.status)}`}>{style.status}</span></div><div className="fine">continuity: {style.continuity_key}</div><div className="code-box" style={{marginTop:12}}>{pretty(style.specification)}</div></article>)}</div></section>

    <section className="section"><div className="section-head"><div><p className="eyebrow">Episodes</p><h2>Continuity ledger</h2></div><span className="fine">No episode can auto-publish while continuity is pending/conflict</span></div><div className="table-wrap"><table><thead><tr><th>Episode</th><th>Status</th><th>Continuity</th><th>Memory</th><th>Summary / next seeds</th></tr></thead><tbody>{episodes.map((ep:any)=><tr key={ep.id}><td><strong>{ep.episode_key}</strong><div className="fine">{ep.title||ep.premise||'—'}</div></td><td><span className={`pill ${pill(ep.status)}`}>{ep.status}</span></td><td><span className={`pill ${pill(ep.continuity_status)}`}>{ep.continuity_status}</span></td><td>{ep.memory_compiled_at?'✓ compiled':'pending'}</td><td><div>{ep.summary||'—'}</div>{Array.isArray(ep.next_episode_seeds)&&ep.next_episode_seeds.length?<div className="fine">Seeds: {ep.next_episode_seeds.slice(0,2).map((x:any)=>x.title||x.premise).join(' · ')}</div>:null}</td></tr>)}</tbody></table></div></section>

    <section className="section split"><div className="card"><p className="eyebrow">Story arcs</p><h2>Open continuity</h2><div className="list">{arcs.map((arc:any)=><div className="list-item" key={arc.arc_key}><div><strong>{arc.title}</strong><div className="fine">{arc.summary}</div></div><span className={`pill ${pill(arc.status)}`}>{arc.status}</span></div>)}{!arcs.length?<div className="empty">No hay arcos persistentes todavía.</div>:null}</div></div><div className="card"><p className="eyebrow">Canonical memory</p><h2>What future episodes remember</h2><div className="list">{memory.slice(0,20).map((m:any)=><div className="list-item" key={`${m.memory_type}:${m.memory_key}`}><div><strong>{m.memory_key}</strong><div className="fine">{m.memory_type} · importance {Math.round(Number(m.importance))}</div></div><span className={`pill ${m.canonical?'good':'warn'}`}>{m.canonical?'canon':'context'}</span></div>)}{!memory.length?<div className="empty">La memoria crecerá al completar episodios.</div>:null}</div></div></section>

    <section className="section card"><div className="section-head"><div><p className="eyebrow">Strategy history</p><h2>Continue / scale / pause</h2></div></div><div className="list">{decisions.map((d:any,i:number)=><div className="list-item" key={i}><div><strong>{d.decision}</strong><div className="fine">score {Number(d.score).toFixed(1)} · confidence {(Number(d.confidence)*100).toFixed(0)}%</div></div><span>{new Date(d.observed_at).toLocaleString()}</span></div>)}{!decisions.length?<div className="empty">Todavía no hay suficiente Analytics para decidir estrategia de serie.</div>:null}</div></section>
  </main></div>;
}
