import Link from 'next/link';
import { requireSession } from '../../lib/auth';
import { query } from '../../lib/db';

export const dynamic = 'force-dynamic';

const providers = [
  { id: 'youtube', name: 'YouTube', icon: '▶', description: 'Sube vídeos y consulta el canal mediante OAuth de Google.', href: '/api/channels/youtube/connect', configured: () => Boolean(process.env.CONTROL_GOOGLE_CLIENT_ID && process.env.CONTROL_GOOGLE_CLIENT_SECRET) },
  { id: 'tiktok', name: 'TikTok', icon: '♪', description: 'Prepara publicación vertical y estado de cuenta TikTok.', href: '/api/channels/tiktok/connect', configured: () => Boolean(process.env.TIKTOK_CLIENT_KEY && process.env.TIKTOK_CLIENT_SECRET) },
  { id: 'instagram', name: 'Instagram', icon: '◎', description: 'Conecta una cuenta profesional mediante Meta Graph.', href: '/api/channels/instagram/connect', configured: () => Boolean(process.env.META_APP_ID && process.env.META_APP_SECRET) },
  { id: 'facebook', name: 'Facebook', icon: 'f', description: 'Conecta páginas mediante Meta Graph y prepara distribución.', href: '/api/channels/facebook/connect', configured: () => Boolean(process.env.META_APP_ID && process.env.META_APP_SECRET) },
] as const;

export default async function ChannelsPage({ searchParams }: { searchParams: Promise<{ connected?: string; error?: string }> }) {
  await requireSession(); const params = await searchParams;
  const channels = await query<any>(`select c.id,c.title,c.youtube_channel_id,c.channel_key,c.lifecycle_state,cc.provider,cc.status as connection_status,cc.updated_at as connected_at from channels c left join channel_connections cc on cc.channel_id=c.id where c.is_owned=true order by c.updated_at desc`);
  const error = params.error ? ({ oauth_config: 'Faltan las credenciales OAuth del proveedor.', oauth_state: 'La autorización caducó; vuelve a intentarlo.', oauth_exchange: 'El proveedor rechazó el intercambio OAuth.', oauth_token: 'El proveedor no devolvió un token utilizable.', channel_lookup: 'No se pudo leer tu canal de YouTube.', no_channel: 'La cuenta no tiene un canal de YouTube disponible.', channel_persist: 'No se pudo guardar la conexión.', provider_unknown: 'Ese proveedor no está disponible.' } as Record<string, string>)[params.error] || (params.error.endsWith('_config') ? `Faltan las credenciales de la aplicación para ${params.error.replace('_config', '')}.` : 'No se pudo conectar el canal.') : '';
  const connected = params.connected ? providers.find((provider) => provider.id === params.connected) : null;
  return <div className="content"><header className="topbar"><div><p className="eyebrow">Distribución</p><h1>Canales conectados</h1><p className="muted">Un solo lugar para conectar destinos y conservar cada autorización cifrada.</p></div><Link className="pill info" href="/">← Inicio</Link></header><main className="main"><section className="cards channel-provider-grid">{providers.map((provider) => { const connection = channels.find((item: any) => item.provider === provider.id && item.connection_status === 'connected'); const configured = provider.configured(); return <article className="card channel-provider-card" key={provider.id}><div className="channel-provider-icon">{provider.icon}</div><div className="row"><h2>{provider.name}</h2><span className={`pill ${connection ? 'good' : configured ? 'info' : 'warn'}`}>{connection ? 'Conectado' : configured ? 'Listo' : 'Requiere configuración'}</span></div><p className="muted">{provider.description}</p>{provider.id === 'youtube' || configured ? <a className="primary" href={provider.href}>{connection ? 'Reconectar' : 'Conectar'}</a> : <span className="fine">Configura las claves OAuth del proveedor en Cloudflare y este botón se activará.</span>}</article>; })}</section>{connected ? <p className="success">{connected.name} conectado correctamente.</p> : null}{error ? <p className="error">{error}</p> : null}<section className="card"><div className="section-head"><div><p className="eyebrow">Cuentas autorizadas</p><h2>Tus canales</h2></div></div>{channels.length ? <div className="channel-list">{channels.map((channel: any) => <div className="list-item" key={`${channel.id}:${channel.provider || 'none'}`}><div><strong>{channel.title}</strong><div className="fine">{channel.provider ? `${channel.provider} · ` : ''}{channel.youtube_channel_id || channel.channel_key}</div></div><span className={`pill ${channel.connection_status === 'connected' ? 'good' : 'warn'}`}>{channel.connection_status === 'connected' ? 'Conectado' : 'Pendiente'}</span></div>)}</div> : <p className="muted">Todavía no hay cuentas propias conectadas.</p>}</section></main></div>;
}
