import { NextResponse } from 'next/server';
import { currentSession } from '../../../lib/auth';
import { query } from '../../../lib/db';

export const runtime = 'nodejs';
function normalizeUrl(value: string) { try { const url = new URL(value.trim()); if (!['http:', 'https:'].includes(url.protocol)) return null; return url.toString(); } catch { return null; } }
function youtubeId(value: string) { try { const url = new URL(value); if (url.hostname.includes('youtu.be')) return url.pathname.split('/').filter(Boolean)[0] || null; if (url.pathname === '/watch') return url.searchParams.get('v'); const parts = url.pathname.split('/').filter(Boolean); return parts[0] === 'shorts' ? parts[1] || null : null; } catch { return null; } }
export async function GET() { const session = await currentSession(); if (!session) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 }); const assets = await query(`select id,title,source_url,asset_kind,thumbnail_url,metadata,created_at from reference_assets where lower(owner_email)=lower($1) order by created_at desc`, [session.email || '']); return NextResponse.json({ ok: true, assets }); }
export async function POST(request: Request) { const session = await currentSession(); if (!session) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 }); const body = await request.json().catch(() => ({})) as Record<string, unknown>; const sourceUrl = normalizeUrl(String(body.url || '')); if (!sourceUrl) return NextResponse.json({ error: 'Introduce una URL pública válida.' }, { status: 400 }); const id = youtubeId(sourceUrl); const title = String(body.title || (id ? `Referencia de YouTube · ${id}` : 'Referencia guardada')).trim().slice(0, 180); const kind = id ? 'youtube' : 'url'; const rows = await query<{ id: string }>(`insert into reference_assets(owner_email,title,source_url,asset_kind,thumbnail_url,metadata) values($1,$2,$3,$4,$5,$6::jsonb) returning id`, [session.email || '', title, sourceUrl, kind, id ? `https://i.ytimg.com/vi/${id}/hqdefault.jpg` : null, JSON.stringify({ youtubeVideoId: id, linkedAt: new Date().toISOString() })]); return NextResponse.json({ ok: true, id: rows[0]?.id || null }); }
export async function DELETE(request: Request) { const session = await currentSession(); if (!session) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 }); const body = await request.json().catch(() => ({})) as Record<string, unknown>; const id = String(body.id || ''); if (!id) return NextResponse.json({ error: 'Falta el id de referencia.' }, { status: 400 }); await query(`delete from reference_assets where id=$1 and lower(owner_email)=lower($2)`, [id, session.email || '']); return NextResponse.json({ ok: true }); }
