import { NodeLocalObjectStore, NodePostgresSqlClient } from '../packages/runtime-node/index.mjs';
import { RunwayMediaProvider } from '@auto-ytb/providers';
import { continuityKey, validateSeriesBible } from '@auto-ytb/os';

const arg=(name,fallback)=>process.argv.find((value)=>value.startsWith(`--${name}=`))?.slice(name.length+3)??fallback;
const req=(name)=>{const value=process.env[name]?.trim();if(!value)throw new Error(`${name} is required`);return value;};
const candidateId=arg('candidate-id');if(!candidateId)throw new Error('Use --candidate-id=<uuid>');
const db=new NodePostgresSqlClient(req('DATABASE_URL'),{ssl:process.env.DATABASE_SSL==='true'?{rejectUnauthorized:false}:undefined});
const store=new NodeLocalObjectStore(process.env.LOCAL_STORAGE_ROOT||'.data/storage');
const imageProvider=new RunwayMediaProvider({apiKey:process.env.IMAGE_API_KEY||process.env.VIDEO_API_KEY||req('VIDEO_API_KEY'),store,imageModel:process.env.IMAGE_MODEL||'gen4_image',videoModel:process.env.VIDEO_MODEL||'gen4.5'});
const model=process.env.TEXT_MODEL_CREATIVE||process.env.TEXT_MODEL_RESEARCH||'gpt-5';
const modelKey=req('TEXT_MODEL_API_KEY');
const arr=(value)=>Array.isArray(value)?value.map(String).filter(Boolean):[];
const slug=(value)=>String(value??'series').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,80)||'series';

const schema={type:'object',additionalProperties:false,required:['title','premise','tone','themes','worldRules','episodeStructure','continuityRules','recurringDevices','audience','characters','styles','promptPack'],properties:{
  title:{type:'string'},premise:{type:'string'},tone:{type:'array',items:{type:'string'}},themes:{type:'array',items:{type:'string'}},worldRules:{type:'array',items:{type:'string'}},episodeStructure:{type:'array',items:{type:'string'}},continuityRules:{type:'array',items:{type:'string'}},recurringDevices:{type:'array',items:{type:'string'}},
  audience:{type:'object',additionalProperties:false,required:['mode','targetAgeMin','targetAgeMax','developmentalStage','vocabularyRules','safetyRules','emotionalRules'],properties:{mode:{type:'string',enum:['GENERAL','MADE_FOR_KIDS']},targetAgeMin:{type:['integer','null']},targetAgeMax:{type:['integer','null']},developmentalStage:{type:['string','null']},vocabularyRules:{type:'array',items:{type:'string'}},safetyRules:{type:'array',items:{type:'string'}},emotionalRules:{type:'array',items:{type:'string'}}}},
  characters:{type:'array',items:{type:'object',additionalProperties:false,required:['key','name','role','invariantFeatures','personalityTraits','speechRules','wardrobeRules','forbiddenChanges','voiceProfile'],properties:{key:{type:'string'},name:{type:'string'},role:{type:'string'},invariantFeatures:{type:'array',items:{type:'string'}},personalityTraits:{type:'array',items:{type:'string'}},speechRules:{type:'array',items:{type:'string'}},wardrobeRules:{type:'array',items:{type:'string'}},forbiddenChanges:{type:'array',items:{type:'string'}},voiceProfile:{type:'object',additionalProperties:true}}}},
  styles:{type:'array',minItems:1,items:{type:'object',additionalProperties:false,required:['key','name','invariantFeatures','palette','compositionRules','motionRules','forbiddenChanges'],properties:{key:{type:'string'},name:{type:'string'},invariantFeatures:{type:'array',items:{type:'string'}},palette:{type:'array',items:{type:'string'}},compositionRules:{type:'array',items:{type:'string'}},motionRules:{type:'array',items:{type:'string'}},forbiddenChanges:{type:'array',items:{type:'string'}}}}},
  promptPack:{type:'object',additionalProperties:false,required:['script','storyboard','image','video','voice','qa'],properties:{script:{type:'array',items:{type:'string'}},storyboard:{type:'array',items:{type:'string'}},image:{type:'array',items:{type:'string'}},video:{type:'array',items:{type:'string'}},voice:{type:'array',items:{type:'string'}},qa:{type:'array',items:{type:'string'}}}}
}};
function responseText(json){if(typeof json.output_text==='string')return json.output_text;for(const item of Array.isArray(json.output)?json.output:[])for(const part of Array.isArray(item.content)?item.content:[])if(typeof part.text==='string')return part.text;throw new Error('Series bootstrap model returned no text');}
async function generateBible(candidate){
  const fingerprint=candidate.style_fingerprint??{},kids=candidate.audience_mode==='MADE_FOR_KIDS';
  const instructions=`You are the showrunner and continuity designer for an original, repeatable YouTube series. Build a production bible that can support many autonomous episodes without character, world, voice or art-style drift. Everything must be original and reusable. ${kids?'This is intentionally made for young children: use developmentally appropriate, emotionally safe storytelling; no graphic danger, unsafe imitation challenges, manipulative purchase pressure, sexual content, humiliation, or overwhelming fear. Define explicit age-specific vocabulary, safety and emotional rules.':''}`;
  const prompt=`Create series bible for candidate ${candidate.proposed_title}. Language: ${candidate.language}. Audience mode: ${candidate.audience_mode}. Target age: ${candidate.target_age_min??'unspecified'}-${candidate.target_age_max??'unspecified'}. Opportunity/style fingerprint: ${JSON.stringify(fingerprint)}. Character seed: ${JSON.stringify(candidate.character_spec??{})}. Requirements: persistent characters need visually measurable invariant features, clothing/accessory rules, speech rules and forbidden changes. The art style needs palette, shape language, composition, motion and forbidden-style changes. Create a repeatable episode structure with fresh-problem potential, world rules, continuity rules, recurring devices and a prompt pack. Do not imitate a named copyrighted franchise or living artist.`;
  const response=await fetch(process.env.TEXT_MODEL_BASE_URL||'https://api.openai.com/v1/responses',{method:'POST',headers:{authorization:`Bearer ${modelKey}`,'content-type':'application/json'},body:JSON.stringify({model,instructions,input:prompt,store:false,text:{format:{type:'json_schema',name:'series_bible_bootstrap',strict:true,schema}}})});
  if(!response.ok)throw new Error(`Series bible model failed ${response.status}: ${(await response.text()).slice(0,800)}`);
  return JSON.parse(responseText(await response.json()));
}
function normalizeBible(raw,candidate){
  const kids=candidate.audience_mode==='MADE_FOR_KIDS',fingerprint=candidate.style_fingerprint??{},audience=raw.audience??{};
  const safety=arr(audience.safetyRules),vocab=arr(audience.vocabularyRules),emotional=arr(audience.emotionalRules);
  if(kids){if(!safety.length)safety.push('No graphic danger or violence','No unsafe imitation challenges or instructions','No manipulative purchase pressure','Resolve frightening situations quickly and safely');if(!vocab.length)vocab.push('Use short concrete age-appropriate sentences','Explain unfamiliar words through context');if(!emotional.length)emotional.push('Never shame or ridicule a child character','End conflict with reassurance, agency and emotional safety');}
  const seriesKey=slug(candidate.candidate_key||candidate.proposed_title),characters=(raw.characters??[]).map((item,index)=>({...item,key:slug(item.key||item.name||`character-${index+1}`),continuityKey:continuityKey(seriesKey,`character:${item.name}:${JSON.stringify(item.invariantFeatures??[])}`),canonicalReferenceUri:null,invariantFeatures:arr(item.invariantFeatures),personalityTraits:arr(item.personalityTraits),speechRules:arr(item.speechRules),wardrobeRules:arr(item.wardrobeRules),forbiddenChanges:arr(item.forbiddenChanges),voiceProfile:item.voiceProfile??{}})),styles=(raw.styles??[]).map((item,index)=>({...item,key:slug(item.key||item.name||`style-${index+1}`),continuityKey:continuityKey(seriesKey,`style:${item.name}:${JSON.stringify(item.invariantFeatures??[])}`),canonicalReferenceUri:null,invariantFeatures:arr(item.invariantFeatures),palette:arr(item.palette),compositionRules:arr(item.compositionRules),motionRules:arr(item.motionRules),forbiddenChanges:arr(item.forbiddenChanges)}));
  return{title:String(raw.title||candidate.proposed_title),language:String(candidate.language||'en'),premise:String(raw.premise||candidate.proposed_title),audience:{mode:kids?'MADE_FOR_KIDS':'GENERAL',targetAgeMin:kids?Number(candidate.target_age_min??audience.targetAgeMin??3):audience.targetAgeMin??null,targetAgeMax:kids?Number(candidate.target_age_max??audience.targetAgeMax??8):audience.targetAgeMax??null,developmentalStage:audience.developmentalStage??null,vocabularyRules:vocab,safetyRules:safety,emotionalRules:emotional},tone:arr(raw.tone),themes:arr(raw.themes).length?arr(raw.themes):arr(fingerprint.themes),worldRules:arr(raw.worldRules),episodeStructure:arr(raw.episodeStructure),continuityRules:arr(raw.continuityRules),recurringDevices:arr(raw.recurringDevices),characters,styles,promptPack:{script:arr(raw.promptPack?.script),storyboard:arr(raw.promptPack?.storyboard),image:arr(raw.promptPack?.image),video:arr(raw.promptPack?.video),voice:arr(raw.promptPack?.voice),qa:arr(raw.promptPack?.qa)}};
}
async function createReferences(bible,seriesKey){
  for(const character of bible.characters){const prompt=`ORIGINAL CANONICAL CHARACTER REFERENCE for a recurring series. ${character.name}, role ${character.role}. Exact invariants: ${character.invariantFeatures.join('; ')}. Wardrobe/accessories: ${character.wardrobeRules.join('; ')}. Personality expressed visually: ${character.personalityTraits.join(', ')}. Produce a clean professional model/reference sheet showing the same character consistently in front, three-quarter and side views plus a small expression row. Neutral simple background. No readable text, no logo, no watermark, no reference to existing franchises or artists. This image is the master identity source for future generations.`;const asset=await imageProvider.generate({prompt,aspectRatio:'16:9'});character.canonicalReferenceUri=asset.uri;character._asset=asset;}
  for(const style of bible.styles){const prompt=`ORIGINAL CANONICAL ART-STYLE REFERENCE for a recurring series. Invariants: ${style.invariantFeatures.join('; ')}. Palette: ${style.palette.join(', ')}. Composition: ${style.compositionRules.join('; ')}. Motion implication: ${style.motionRules.join('; ')}. Avoid: ${style.forbiddenChanges.join('; ')}. Show one representative environment and one simple recurring-character silhouette language without readable text, logos or imitation of named artists/franchises. This is a master style reference.`;const asset=await imageProvider.generate({prompt,aspectRatio:'16:9'});style.canonicalReferenceUri=asset.uri;style._asset=asset;}
  return bible;
}

try{
  const candidate=(await db.query(`select sc.*,c.channel_key,c.title as channel_title,c.language as channel_language,c.niche from series_candidates sc join channels c on c.id=sc.channel_id where sc.id=$1`,[candidateId])).rows[0];if(!candidate)throw new Error(`Series candidate ${candidateId} not found`);
  await db.query(`update series_candidates set status='bootstrapping',updated_at=now() where id=$1`,[candidateId]);
  let bible=normalizeBible(await generateBible(candidate),candidate);const validationBefore=validateSeriesBible(bible);if(!validationBefore.valid)throw new Error(`Generated series bible invalid: ${validationBefore.issues.join(', ')}`);
  bible=await createReferences(bible,candidate.candidate_key);const validation=validateSeriesBible(bible);if(!validation.valid)throw new Error(`Series bible/reference validation failed: ${validation.issues.join(', ')}`);
  const seriesKey=slug(candidate.candidate_key),seriesContinuityKey=continuityKey(seriesKey,`series-v1:${bible.premise}:${JSON.stringify(bible.worldRules)}`),bibleContinuityKey=continuityKey(seriesKey,`bible-v1:${JSON.stringify(bible.continuityRules)}`);
  const created=await db.transaction(async(tx)=>{
    const series=(await tx.query(`insert into series (channel_id,series_key,title,language,positioning,audience_mode,target_age_min,target_age_max,lifecycle_state,automation_enabled,current_bible_version,continuity_key,identity,format_strategy,performance_policy)
      values ($1,$2,$3,$4,$5,$6,$7,$8,'active',true,1,$9,$10::jsonb,$11::jsonb,$12::jsonb)
      on conflict (channel_id,series_key) do update set title=excluded.title,language=excluded.language,positioning=excluded.positioning,audience_mode=excluded.audience_mode,target_age_min=excluded.target_age_min,target_age_max=excluded.target_age_max,lifecycle_state='active',automation_enabled=true,current_bible_version=greatest(series.current_bible_version,1),continuity_key=coalesce(series.continuity_key,excluded.continuity_key),identity=excluded.identity,format_strategy=excluded.format_strategy,updated_at=now() returning id`,[candidate.channel_id,seriesKey,bible.title,bible.language,bible.premise,bible.audience.mode,bible.audience.targetAgeMin??null,bible.audience.targetAgeMax??null,seriesContinuityKey,JSON.stringify({themes:bible.themes,styleTags:bible.styles.flatMap((s)=>[s.name,...s.invariantFeatures]).slice(0,20),characterMode:bible.characters.length?'persistent-character':'none'}),JSON.stringify({formats:['LONG_HORIZONTAL','SHORT_VERTICAL']}),JSON.stringify({optimizeFor:'RETENTION_PROFIT_CONTINUITY'})])).rows[0];
    await tx.query(`update series_bibles set status='retired' where series_id=$1 and status='active'`,[series.id]);
    const bibleRow=(await tx.query(`insert into series_bibles (series_id,version,status,continuity_key,bible,validation,activated_at) values ($1,1,'active',$2,$3::jsonb,$4::jsonb,now()) on conflict (series_id,version) do update set status='active',continuity_key=excluded.continuity_key,bible=excluded.bible,validation=excluded.validation,activated_at=now() returning id`,[series.id,bibleContinuityKey,JSON.stringify(bible),JSON.stringify(validation)])).rows[0];
    await tx.query(`delete from series_characters where series_id=$1`,[series.id]);await tx.query(`delete from series_styles where series_id=$1`,[series.id]);
    for(const character of bible.characters){await tx.query(`insert into series_characters (series_id,character_key,name,role,continuity_key,specification,voice_profile,canonical_reference_uri,status) values ($1,$2,$3,$4,$5,$6::jsonb,$7::jsonb,$8,'active')`,[series.id,character.key,character.name,character.role??null,character.continuityKey,JSON.stringify({invariantFeatures:character.invariantFeatures,personalityTraits:character.personalityTraits,speechRules:character.speechRules,wardrobeRules:character.wardrobeRules,forbiddenChanges:character.forbiddenChanges}),JSON.stringify(character.voiceProfile??{}),character.canonicalReferenceUri]);if(character._asset)await tx.query(`insert into series_assets (series_id,scope_type,scope_key,asset_type,uri,provider,model,continuity_key,license,metadata) values ($1,'character',$2,'canonical_reference',$3,$4,$5,$6,'original-generated',$7::jsonb) on conflict do nothing`,[series.id,character.key,character._asset.uri,character._asset.provider,character._asset.model??null,character.continuityKey,JSON.stringify({candidateId,promptPurpose:'canonical-character-reference'})]);}
    for(const style of bible.styles){await tx.query(`insert into series_styles (series_id,style_key,name,continuity_key,specification,canonical_reference_uri,status) values ($1,$2,$3,$4,$5::jsonb,$6,'active')`,[series.id,style.key,style.name,style.continuityKey,JSON.stringify({invariantFeatures:style.invariantFeatures,palette:style.palette,compositionRules:style.compositionRules,motionRules:style.motionRules,forbiddenChanges:style.forbiddenChanges}),style.canonicalReferenceUri]);if(style._asset)await tx.query(`insert into series_assets (series_id,scope_type,scope_key,asset_type,uri,provider,model,continuity_key,license,metadata) values ($1,'style',$2,'canonical_reference',$3,$4,$5,$6,'original-generated',$7::jsonb) on conflict do nothing`,[series.id,style.key,style._asset.uri,style._asset.provider,style._asset.model??null,style.continuityKey,JSON.stringify({candidateId,promptPurpose:'canonical-style-reference'})]);}
    await tx.query(`insert into series_prompt_packs (series_id,version,status,prompts) values ($1,1,'active',$2::jsonb) on conflict (series_id,version) do update set status='active',prompts=excluded.prompts`,[series.id,JSON.stringify(bible.promptPack)]);
    await tx.query(`update series_candidates set status='active',updated_at=now() where id=$1`,[candidateId]);
    return{seriesId:series.id,bibleId:bibleRow.id};
  });
  console.log(JSON.stringify({candidateId,seriesId:created.seriesId,bibleId:created.bibleId,seriesKey,bibleVersion:1,validation,characters:bible.characters.map((c)=>({name:c.name,continuityKey:c.continuityKey,reference:c.canonicalReferenceUri})),styles:bible.styles.map((s)=>({name:s.name,continuityKey:s.continuityKey,reference:s.canonicalReferenceUri}))},null,2));
}catch(error){await db.query(`update series_candidates set status='discovered',updated_at=now() where id=$1`,[candidateId]).catch(()=>{});throw error;}finally{await db.close();}
