import { buildGenerationModePlan, buildReferencePack, buildShotPlan, buildStoryArchitecture, CONTENT_FORMAT_PROFILES, createProductionJob, createResearchPack, deconstructWinningVideo, engineerHooks, evaluateBenchmarkQualityGates, evaluateProductionReadiness, extractContentDNA, generateThumbnailConcepts, generateTitleCandidates, generateSeriesExpansion, generateEvidenceBackedOpportunity, getContentFormatProfile, minePatternClusters, normalizeBenchmarkVideo, rankPackagingCandidates, repairTimeline, analyzeSynchronization, buildWinnerExpansionPlan } from '../packages/core/dist/index.js';
import { createDefaultProviderRegistry, ProviderRouter } from '../packages/providers/dist/index.js';
import { buildSeriesContinuityContext, continuityKey, validateSeriesBible } from '../packages/os/dist/index.js';

const now = new Date('2026-09-13T00:00:00.000Z');
const baseChannel = { id: 'klyverio-fixture', name: 'Klyverio fixture', handle: '@klyverio', subscribers: 45_000, totalViews: 4_000_000, totalVideos: 24, niche: 'umbrella-opportunity-driven', recentUploadFrequencyPerWeek: 1.5, estimatedViewsPerMonth: 1_000_000, recentMomentum: 76, source: 'fixture', observedAt: now.toISOString() };
const rawVideos = Array.from({ length: 8 }, (_, index) => ({ id: `smoke-${index}`, channelId: baseChannel.id, title: index < 4 ? [`Why This System Was Never Stable`, `How One Small Choice Reshaped the Market`, `The Hidden Cost Behind a Breakthrough`, `What Really Happened to the Failed Plan?`][index] : `Evidence Story ${index}`, publishDate: new Date(now.getTime() - (index + 1) * 86_400_000).toISOString(), durationSeconds: 480 + index * 15, views: index < 4 ? 320_000 - index * 30_000 : 55_000 - index * 2_000, likes: 6_000, comments: 600, channelSubscribers: baseChannel.subscribers, topic: 'the hidden mechanism behind market success' }));
const videos = rawVideos.map((video) => normalizeBenchmarkVideo({ ...video, comparable: rawVideos, now }));
const dnaById = Object.fromEntries(videos.map((video) => [video.id, extractContentDNA({ channel: baseChannel, video, topic: video.topic })]));
const patterns = minePatternClusters({ videos, dnaByVideoId: dnaById });
const pack = buildReferencePack({ niche: baseChannel.niche, topic: videos[0].topic, channels: [baseChannel], videos, dnaByVideoId: dnaById, patterns });
const opportunity = generateEvidenceBackedOpportunity({ request: { niche: baseChannel.niche, language: 'en', format: 'LONG_FORM' }, topic: 'the hidden mechanism behind market success', angle: 'test a new entity against the mechanism', workingTitle: 'Why This System Changed', audience: 'global English-speaking viewers', videos, patterns, referencePack: pack });
const registry = createDefaultProviderRegistry({});
const router = new ProviderRouter(registry);

function runFormat(formatName) {
  const profile = CONTENT_FORMAT_PROFILES[formatName];
  const winner = videos[0];
  const viralTemplate = deconstructWinningVideo(winner, dnaById[winner.id]);
  const hooks = engineerHooks({ topic: opportunity.topic, promise: opportunity.audience, dna: dnaById[winner.id] });
  const titles = generateTitleCandidates({ topic: opportunity.topic, angle: opportunity.angle, referencePack: pack, patterns, referenceTitles: videos.map((video) => video.title) });
  const thumbnails = generateThumbnailConcepts({ topic: opportunity.topic, title: titles[0].text, referencePack: pack, patterns, dna: dnaById[winner.id] });
  const packaging = rankPackagingCandidates({ titles, thumbnails });
  const research = createResearchPack({ topic: opportunity.topic, referenceSources: pack.items.map((item) => ({ id: `ref-${item.videoId}`, url: `fixture://${item.videoId}`, title: item.title, sourceType: 'REFERENCE', quality: 70 })), factSources: formatName === 'CHARACTER_SERIES' ? [] : [{ id: 'fact-1', url: 'fixture://primary/fact-1', title: 'Fixture primary source', sourceType: 'PRIMARY', quality: 90 }], claims: formatName === 'CHARACTER_SERIES' ? [] : [{ id: 'claim-1', claim: 'The central mechanism is observable in the supplied sources.', sourceIds: ['fact-1'], importance: 'CRITICAL', confidence: 90 }] });
  const architecture = buildStoryArchitecture({ format: profile.benchmarkFormat, topic: opportunity.topic, promise: opportunity.audience, targetDurationSeconds: profile.targetDurationSeconds, research, referencePack: pack });
  const shotPlan = buildShotPlan({ architecture, sourceBacked: formatName !== 'CHARACTER_SERIES' });
  const job = createProductionJob({ id: `${formatName.toLowerCase()}-fixture`, title: titles[0].text, script: { durationSeconds: profile.targetDurationSeconds }, shotPlan, formatProfile: profile, channelBible: formatName === 'CHARACTER_SERIES' ? { series: 'The Mechanism Club' } : undefined, budgetUsd: 5 }, router);
  const narration = architecture.beats.map((beat) => ({ id: `n-${beat.id}`, startSeconds: beat.targetStartSeconds, durationSeconds: beat.targetDurationSeconds, text: beat.newInformation, beatId: beat.id }));
  const timeline = { narration, scenes: shotPlan.scenes.map((scene) => ({ id: scene.id, startSeconds: scene.startSeconds, durationSeconds: scene.durationSeconds, kind: scene.visualType, narrationSegmentIds: [`n-${scene.beatId}`] })), audio: [{ id: 'voice', kind: 'VOICE', startSeconds: 0, durationSeconds: profile.targetDurationSeconds, gain: 0.8 }], captions: narration.map((item) => ({ id: `c-${item.id}`, startSeconds: item.startSeconds, endSeconds: item.startSeconds + item.durationSeconds, text: item.text, narrationSegmentId: item.id })) };
  const sync = analyzeSynchronization(timeline);
  const gates = evaluateBenchmarkQualityGates({ referencePack: pack, packaging, originality: { status: 'PASS', titleSimilarity: 0, hookSimilarity: 0, phraseOverlap: 0, semanticScriptSimilarity: 0, structuralSimilarity: 0.4, thumbnailConceptSimilarity: 0, assetProvenance: 'CLEARED', reasons: ['fixture-original'], thresholds: { warn: 0.45, fail: 0.72 } }, research, hooks: { length: hooks.length }, story: architecture, shotPlan, cost: { allowed: job.estimatedCostUsd <= 5, estimatedCostUsd: job.estimatedCostUsd, budgetUsd: 5 }, sync: sync.pass, audio: true, copyright: true, ypp: true, render: false });
  const readiness = evaluateProductionReadiness({ referencePack: pack, packaging, originality: { status: 'PASS', titleSimilarity: 0, hookSimilarity: 0, phraseOverlap: 0, semanticScriptSimilarity: 0, structuralSimilarity: 0.4, thumbnailConceptSimilarity: 0, assetProvenance: 'CLEARED', reasons: ['fixture-original'], thresholds: { warn: 0.45, fail: 0.72 } }, research, hooks: { length: hooks.length }, story: architecture, shotPlan, cost: { allowed: job.estimatedCostUsd <= 5, estimatedCostUsd: job.estimatedCostUsd, budgetUsd: 5 }, providerPass: job.tasks.every((task) => task.providerStatus !== 'NO_CREDENTIALS'), seriesRelevant: formatName === 'CHARACTER_SERIES', seriesContinuityPass: formatName === 'CHARACTER_SERIES', sync: sync.pass, audio: true, visual: false, copyright: true, ypp: true, render: false });
  const expansion = buildWinnerExpansionPlan({ winner, contentDNA: dnaById[winner.id], viralTemplate, referencePack: pack, analyticsAvailable: false });
  return { format: formatName, profile: { aspectRatio: profile.aspectRatio, duration: profile.targetDurationSeconds, researchDepth: profile.researchDepth }, chain: { references: pack.items.length, hooks: hooks.length, titles: titles.length, thumbnails: thumbnails.length, packaging: packaging.length, storyBeats: architecture.beats.length, scenes: shotPlan.scenes.length, productionTasks: job.tasks.length, seriesCandidates: expansion.candidates.length }, providerStatuses: job.tasks.reduce((result, task) => ({ ...result, [task.kind]: task.providerStatus }), {}), synchronization: sync, quality: gates, readiness: { readyForFinal: readiness.readyForFinal, readyForRelease: readiness.readyForRelease, blockers: readiness.blockers }, productionState: job.status, draft: buildGenerationModePlan('DRAFT', { budgetUsd: 5, estimatedCostUsd: job.estimatedCostUsd }), final: buildGenerationModePlan('FINAL', { budgetUsd: 5, estimatedCostUsd: job.estimatedCostUsd, validated: false }) };
}

const seriesBible = { title: 'The Mechanism Club', language: 'en', premise: 'A curious team tests hidden mechanisms in a changing world.', audience: { mode: 'GENERAL', vocabularyRules: [], safetyRules: [], emotionalRules: [] }, tone: ['curious'], themes: ['discovery'], worldRules: ['evidence matters'], episodeStructure: ['problem', 'attempt', 'payoff'], continuityRules: ['characters retain identity'], recurringDevices: ['evidence board'], characters: [{ key: 'mara', name: 'Mara', continuityKey: 'mara-v1', invariantFeatures: ['red scarf'], personalityTraits: ['curious'], speechRules: ['short concrete lines'], wardrobeRules: ['red scarf'], forbiddenChanges: ['do not change red scarf'], voiceProfile: { voiceId: 'fixture-mara' }, canonicalReferenceUri: 'fixture://mara' }], styles: [{ key: 'club', name: 'Club style', continuityKey: 'club-v1', invariantFeatures: ['flat editorial shapes'], palette: ['navy', 'amber'], compositionRules: ['clear focal subject'], motionRules: ['restrained push'], forbiddenChanges: ['no photoreal drift'], canonicalReferenceUri: 'fixture://club' }], promptPack: { script: [], storyboard: [], image: [], video: [], voice: [], qa: [] } };
if (!validateSeriesBible(seriesBible).valid) throw new Error('series bible fixture invalid');
const requestedFormat = process.argv[2]?.toUpperCase();
const outputs = ['DOCUMENTARY', 'RANKING', 'CHARACTER_SERIES'].filter((format) => !requestedFormat || requestedFormat === format).map(runFormat);
if (!outputs.length) throw new Error(`Unknown format ${requestedFormat}`);
const continuity = buildSeriesContinuityContext({ profile: { seriesId: 'series-fixture', seriesKey: 'mechanism-club', channelId: baseChannel.id, title: seriesBible.title, language: 'en', audienceMode: 'GENERAL', themes: ['discovery'], styleTags: ['editorial'], formats: ['CHARACTER_SERIES'], characterMode: 'persistent-character', characterNames: ['Mara'], enabled: true }, bible: seriesBible, bibleVersion: 1, continuityKey: continuityKey('mechanism-club', 'mara'), episodeNumber: 1 });
console.log(JSON.stringify({ mode: 'FIXTURE', paidOperations: 0, formats: outputs, series: { bibleValid: true, continuityKey: continuity.continuityKey, episodeKey: continuity.episodeKey, characterKeys: continuity.characterContinuityKeys }, note: 'Plan-only smoke: no provider artifact is fabricated and no paid provider is called.' }, null, 2));
