import { spawn } from 'node:child_process';
import os from 'node:os';
import { NodePostgresSqlClient } from '../packages/runtime-node/index.mjs';
import { computeRetryDelayMs, shouldRetry } from '@auto-ytb/os';
import { projectChannelCredentials } from './lib/channel-env.mjs';
import { createRuntimeHeartbeat } from './lib/runtime-heartbeat.mjs';

const req=(name)=>{const value=process.env[name]?.trim();if(!value)throw new Error(`${name} is required`);return value;};
const num=(name,fallback)=>{const value=Number(process.env[name]??fallback);if(!Number.isFinite(value))throw new Error(`${name} must be numeric`);return value;};
const once=process.argv.includes('--once');
const maxJobsArg=process.argv.find((arg)=>arg.startsWith('--max-jobs='));
const maxJobs=Math.max(1,Math.floor(Number(maxJobsArg?.slice(11)||(once?1:1000000))));
const pollMs=Math.max(1000,num('JOB_POLL_MS',1000));
const staleMinutes=Math.max(5,num('JOB_STALE_MINUTES',120));
const timeoutMinutes=Math.max(5,num('JOB_TIMEOUT_MINUTES',120));
const leaseMs=Math.max(30_000,num('JOB_LEASE_MS',120_000));
const distributionPollSeconds=Math.max(15,num('DISTRIBUTION_POLL_SECONDS',60));
const distributionMaxPolls=Math.max(1,Math.min(100,Math.floor(num('DISTRIBUTION_MAX_POLLS',30))));
const workerRole=String(process.env.WORKER_ROLE||'all').trim().toLowerCase();
const workerId=`${os.hostname()}:${process.pid}`;
const db=new NodePostgresSqlClient(req('DATABASE_URL'),{ssl:process.env.DATABASE_SSL==='true'?{rejectUnauthorized:false}:undefined});
const heartbeat=createRuntimeHeartbeat(db,{role:workerRole==='background'?'background-worker':'worker',instanceId:workerId,minIntervalMs:10_000});
let processed=0,stopping=false,activeJob=null,activeChild=null,shutdownRequeuePromise=null;
async function requeueActiveJob(reason){
  if(!activeJob||shutdownRequeuePromise)return shutdownRequeuePromise;
  const job=activeJob;
  shutdownRequeuePromise=(async()=>{
    const result=await db.query(`update jobs set state='retry',locked_at=null,locked_by=null,lease_owner=null,lease_expires_at=null,heartbeat_at=now(),not_before=now(),last_error=$3,updated_at=now() where id=$1 and state='running' and lease_owner=$2`,[job.id,workerId,reason]);
    if(result.rowCount)await emit(job.id,'shutdown_requeued',{workerId,attempt:job.attempts,reason});
  })().catch((error)=>console.error(`[worker] shutdown requeue failed: ${error instanceof Error?error.message:String(error)}`));
  return shutdownRequeuePromise;
}
function requestStop(reason){
  stopping=true;
  if(activeChild){try{activeChild.kill('SIGTERM');}catch{}setTimeout(()=>{try{activeChild?.kill('SIGKILL');}catch{}},2500).unref();}
  void requeueActiveJob(reason);
}
process.on('SIGTERM',()=>requestStop('Worker stopped during deployment; production will resume automatically.'));
process.on('SIGINT',()=>requestStop('Worker interrupted; production will resume automatically.'));
const sleep=(ms)=>new Promise((resolve)=>setTimeout(resolve,ms));
async function emit(jobId,eventType,detail={}){await db.query(`insert into job_events (job_id,event_type,detail) values ($1,$2,$3::jsonb)`,[jobId,eventType,JSON.stringify(detail)]);}
async function recoverStale(){const result=await db.query(`update jobs set state='retry',locked_at=null,locked_by=null,lease_owner=null,lease_expires_at=null,heartbeat_at=now(),not_before=now(),last_error=coalesce(last_error,'') || case when last_error is null or last_error='' then '' else E'\n' end || 'Recovered stale running job',updated_at=now() where state='running' and (lease_expires_at < now() or (lease_expires_at is null and locked_at < now()-($1::text || ' minutes')::interval)) returning id`,[String(staleMinutes)]);for(const row of result.rows)await emit(row.id,'stale_recovered',{workerId,staleMinutes});return result.rows.length;}
const claimKindFilter=workerRole==='interactive' ? "and kind='produce_opportunity'" : workerRole==='background' ? "and kind<>'produce_opportunity'" : '';
async function claim(){const result=await db.query(`with candidate as (select id from jobs where state in ('queued','retry') ${claimKindFilter} and not_before<=now() order by priority desc,created_at asc for update skip locked limit 1) update jobs j set state='running',attempts=j.attempts+1,locked_at=now(),locked_by=$1,lease_owner=$1,lease_expires_at=now()+($2::text||' milliseconds')::interval,heartbeat_at=now(),updated_at=now() from candidate where j.id=candidate.id returning j.*`,[workerId,String(leaseMs)]);const job=result.rows[0];if(job)await emit(job.id,'started',{workerId,attempt:job.attempts,kind:job.kind,channelId:job.channel_id,credentialsRef:job.payload?.credentialsRef,contentFormat:job.payload?.contentFormat,contentArchetype:job.payload?.contentArchetype?.archetype??null,brandContinuityRequired:Boolean(job.payload?.brandContext?.required),brandVersion:job.payload?.brandContext?.brandVersion??null,seriesId:job.payload?.seriesId??null,seriesKey:job.payload?.seriesKey??null,seriesEpisodeId:job.payload?.seriesEpisodeId??null,platform:job.payload?.platform??null});return job;}
function runNode(script,args=[],envOverrides={}){return new Promise((resolve,reject)=>{const child=spawn(process.execPath,[script,...args],{cwd:process.cwd(),env:{...process.env,...envOverrides},stdio:['ignore','pipe','pipe']});activeChild=child;let stdout='',stderr='';const append=(current,chunk)=>`${current}${chunk.toString()}`.slice(-30000);child.stdout.on('data',(chunk)=>{stdout=append(stdout,chunk);process.stdout.write(chunk);});child.stderr.on('data',(chunk)=>{stderr=append(stderr,chunk);process.stderr.write(chunk);});const timer=setTimeout(()=>{child.kill('SIGTERM');setTimeout(()=>child.kill('SIGKILL'),10000).unref();},timeoutMinutes*60_000);const finish=(fn)=>{if(activeChild===child)activeChild=null;fn();};child.on('error',(error)=>{clearTimeout(timer);finish(()=>reject(error));});child.on('exit',(code,signal)=>{clearTimeout(timer);finish(()=>{if(code===0)resolve({stdout,stderr});else reject(new Error(`child process failed code=${code} signal=${signal??'none'} stderr=${stderr.slice(-4000)}`));});});});}
function channelEnv(payload){return projectChannelCredentials(process.env,String(payload?.credentialsRef??'PRIMARY'));}
function archiveConfigured(env=process.env){const provider=String(env.CONTENT_LIBRARY_PROVIDER||'cloudflare-r2').toLowerCase();if(['cloudflare-r2','r2'].includes(provider))return Boolean(String(env.AUTO_YTB_MEDIA_PROXY_URL??'').trim()&&String(env.CONTROL_PLANE_TOKEN??'').trim());return ['DRIVE_CLIENT_ID','DRIVE_CLIENT_SECRET','DRIVE_REFRESH_TOKEN','DRIVE_ROOT_FOLDER_ID'].every((name)=>String(env[name]??'').trim().length>0);}
async function latestRunForOpportunity(opportunityId){return (await db.query(`select pr.id,pr.content_idea_id,coalesce(pr.total_cost_usd,0)::float as cost from production_runs pr join content_ideas ci on ci.id=pr.content_idea_id where ci.opportunity_id=$1 order by pr.created_at desc limit 1`,[opportunityId])).rows[0]??null;}
async function persistMeter(productionRunId,session,scoped){if(!productionRunId)return;await runNode('scripts/persist-cost-events.mjs',[`--production-run-id=${productionRunId}`,`--session=${session}`],scoped);}
async function linkProductionContext(payload,productionRunId,contentIdeaId){if(!productionRunId)return;await db.transaction(async(tx)=>{if(payload?.seriesId&&contentIdeaId)await tx.query(`update content_ideas set series_id=$2 where id=$1`,[contentIdeaId,payload.seriesId]);await tx.query(`update production_runs set metadata=metadata||$2::jsonb,updated_at=now() where id=$1`,[productionRunId,JSON.stringify({seriesContext:payload?.seriesContext??null,seriesId:payload?.seriesId??null,seriesKey:payload?.seriesKey??null,seriesEpisodeId:payload?.seriesEpisodeId??null,seriesAutomationProfile:payload?.seriesContext?.automationProfile??null,seriesAutomationProfileVersion:payload?.seriesContext?.automationProfileVersion??null,contentArchetype:payload?.contentArchetype??null,scheduledExecutionPlan:payload?.executionPlan??null,reservedCostUsd:Number(payload?.reservedCostUsd??0)})]);if(payload?.seriesEpisodeId)await tx.query(`update series_episodes set production_run_id=$2,title=coalesce(title,$3),premise=coalesce(premise,$3),status=$4,continuity_snapshot=$5::jsonb,updated_at=now() where id=$1`,[payload.seriesEpisodeId,productionRunId,payload.topic??null,process.env.AUTO_UPLOAD_PRIVATE==='true'?'private':'production',JSON.stringify(payload.seriesContext??{})]);});}
async function scheduleDistributionPoll(job,row){const payload=job.payload??{},sequence=Math.max(0,Number(payload.pollSequence??0))+1;if(row?.state!=='processing')return null;if(sequence>distributionMaxPolls){await db.query(`update distribution_attempts set state='failed',last_error=$3,updated_at=now() where publication_id=$1 and platform=$2`,[payload.publicationId,payload.platform,`Distribution processing exceeded ${distributionMaxPolls} status polls`]);return null;}const key=`distribution-poll:${payload.publicationId}:${payload.platform}:${sequence}`,next={...payload,pollSequence:sequence,source:'distribution-processing-poll'};const inserted=await db.query(`insert into jobs (job_key,kind,channel_id,state,priority,max_attempts,not_before,payload) values ($1,'distribute_publication',$2,'queued',90,4,now()+($3::text||' seconds')::interval,$4::jsonb) on conflict (job_key) do nothing returning id`,[key,job.channel_id??null,String(distributionPollSeconds),JSON.stringify(next)]);return inserted.rows[0]?.id??null;}

async function execute(job){
  const payload=job.payload??{};
  if(job.kind==='produce_opportunity'){
    const topic=String(payload.topic??'').trim();if(!topic)throw new Error('produce_opportunity job missing payload.topic');
    const contentFormat=String(payload.contentFormat??'LONG_HORIZONTAL'),channelConfig=String(payload.channelConfigPath??payload.channelConfig??process.env.CHANNEL_CONFIG??'config/channels/future-tech-business.example.json'),meterSession=`${job.id}-attempt-${job.attempts}`;
    const seriesAutomationProfile=payload.seriesContext?.automationProfile??{};
    const scoped={...channelEnv(payload),AUTO_YTB_METER_SESSION_ID:meterSession,AUTO_YTB_CHANNEL_ID:String(payload.channelId??job.channel_id??''),AUTO_YTB_CHANNEL_KEY:String(payload.channelKey??''),AUTO_YTB_CONTENT_TOPIC:topic,AUTO_YTB_CONTENT_FORMAT:contentFormat,AUTO_YTB_VIDEO_ONLY:String(payload.ui?.videoOnly??process.env.AUTO_YTB_VIDEO_ONLY??'false'),AUTO_YTB_PRODUCTION_MODE:String(payload.ui?.requestedMode??process.env.AUTO_YTB_PRODUCTION_MODE??'AUTO'),AUTO_YTB_SOURCE_MODE:String(payload.ui?.sourceMode??process.env.AUTO_YTB_SOURCE_MODE??''),AUTO_YTB_VISUAL_STYLE:String(payload.ui?.visualStyle??process.env.AUTO_YTB_VISUAL_STYLE??''),AUTO_YTB_QUALITY_MODE:String(payload.ui?.qualityMode??'MAX_QUALITY'),AUTO_YTB_REQUESTED_DURATION_SEC:String(payload.ui?.durationSec??''),AUTO_YTB_BRAND_CONTEXT:JSON.stringify(payload.brandContext??{}),AUTO_YTB_SERIES_CONTEXT:JSON.stringify(payload.seriesContext??{}),AUTO_YTB_SERIES_AUTOMATION_PROFILE:JSON.stringify(seriesAutomationProfile),AUTO_YTB_SERIES_AUTOMATION_PROFILE_VERSION:String(payload.seriesContext?.automationProfileVersion??''),AUTO_YTB_CONTENT_ARCHETYPE_PROFILE:payload.contentArchetype?.profile?JSON.stringify(payload.contentArchetype.profile):'',AUTO_YTB_CONTENT_ARCHETYPE_DECISION:payload.contentArchetype?JSON.stringify(payload.contentArchetype):''};
    await emit(job.id,'production_stage',{stage:'RESEARCH',message:'Investigación y selección de vídeo en movimiento iniciadas.',workerId,attempt:job.attempts});
    try{await runNode('scripts/live-pipeline.mjs',[`--topic=${topic}`,`--opportunity-id=${job.opportunity_id}`,`--format=${contentFormat}`,`--channel-config=${channelConfig}`],{...scoped,AUTO_YTB_JOB_ID:String(job.id)});}catch(error){const failedRun=await latestRunForOpportunity(job.opportunity_id);if(failedRun?.id){await linkProductionContext(payload,failedRun.id,failedRun.content_idea_id).catch(()=>{});await persistMeter(failedRun.id,meterSession,scoped).catch(()=>{});}await emit(job.id,'production_stage',{stage:'QA',message:`La ejecución se detuvo: ${error instanceof Error?error.message:String(error)}`}).catch(()=>{});throw error;}
    const runResult=await latestRunForOpportunity(job.opportunity_id),productionRunId=runResult?.id;
    await emit(job.id,'production_stage',{stage:'ARCHIVED',message:'Render terminado; persistiendo archivos y metadatos de la producción.',productionRunId}).catch(()=>{});
     if(productionRunId){
       await linkProductionContext(payload,productionRunId,runResult.content_idea_id);
       // The render and its R2 mirror are already durable at this point. Move
       // ledger/fingerprint/archive work behind the interactive completion so
       // the user sees a finished video instead of waiting on bookkeeping.
       const postKey=`postprocess-production:${productionRunId}`;
       const postPayload={...payload,productionRunId,contentIdeaId:runResult.content_idea_id,meterSession,channelConfigPath:channelConfig};
       await db.query(`insert into jobs (job_key,kind,channel_id,state,priority,max_attempts,payload) values ($1,'postprocess_production',$2,'queued',20,3,$3::jsonb) on conflict (job_key) do nothing`,[postKey,job.channel_id??null,JSON.stringify(postPayload)]);
       if(process.env.AUTO_UPLOAD_PRIVATE==='true')await db.query(`insert into jobs (job_key,kind,channel_id,state,priority,max_attempts,payload) values ($1,'publish_production',$2,'queued',15,3,$3::jsonb) on conflict (job_key) do nothing`,[`publish-production:${productionRunId}`,job.channel_id??null,JSON.stringify(postPayload)]);
     }
    const reconciled=productionRunId?(await db.query(`select total_cost_usd::float as cost from production_runs where id=$1`,[productionRunId])).rows[0]:null;
    await emit(job.id,'production_stage',{stage:'READY_FOR_REVIEW',message:'Producción lista para revisar.',productionRunId}).catch(()=>{});
     return{actualCostUsd:Number(reconciled?.cost??runResult?.cost??0),contentFormat,productionRunId,costMeterSession:meterSession,contentArchetype:payload.contentArchetype?.archetype??null,brandContinuityRequired:Boolean(payload.brandContext?.required),brandVersion:payload.brandContext?.brandVersion??null,seriesId:payload.seriesId??null,seriesKey:payload.seriesKey??null,seriesEpisodeId:payload.seriesEpisodeId??null};
   }
  if(job.kind==='postprocess_production'){
    const productionRunId=String(payload.productionRunId??'').trim();
    if(!productionRunId)throw new Error('postprocess_production requires productionRunId');
    const scoped=channelEnv(payload);
    await persistMeter(productionRunId,String(payload.meterSession??`${job.id}-postprocess`),scoped);
    await runNode('scripts/persist-creative-fingerprint.mjs',[`--production-run-id=${productionRunId}`],scoped);
    await runNode('scripts/economics-sync.mjs',[],scoped);
    if(process.env.CONTENT_LIBRARY_ENABLED!=='false'&&archiveConfigured({...process.env,...scoped}))await runNode('scripts/finalize-production.mjs',[`--production-run-id=${productionRunId}`,`--channel-config=${payload.channelConfigPath??'config/channels/future-tech-business.example.json'}`],scoped);
    return{productionRunId};
  }
  if(job.kind==='publish_production'){
    const productionRunId=String(payload.productionRunId??'').trim();
    if(!productionRunId)throw new Error('publish_production requires productionRunId');
    await runNode('scripts/auto-publish.mjs',[`--production-run-id=${productionRunId}`,`--channel-config=${payload.channelConfigPath??'config/channels/future-tech-business.example.json'}`],channelEnv(payload));
    return{productionRunId};
  }
  if(job.kind==='upload_private_production'){
    const productionRunId=String(payload.productionRunId??'').trim();
    if(!productionRunId)throw new Error('upload_private_production requires productionRunId');
    await runNode('scripts/upload-private-production.mjs',[`--production-run-id=${productionRunId}`],channelEnv(payload));
    const row=(await db.query(`select p.id as publication_id,p.youtube_video_id from publications p where p.production_run_id=$1 order by p.updated_at desc limit 1`,[productionRunId])).rows[0]??null;
    return{productionRunId,publicationId:row?.publication_id??null,externalId:row?.youtube_video_id??null,platform:'youtube'};
  }
  if(job.kind==='bootstrap_channel_brand'){const candidateId=String(payload.candidateId??'').trim(),channelId=String(payload.channelId??job.channel_id??'').trim();if(!candidateId&&!channelId)throw new Error('bootstrap_channel_brand requires candidateId or channelId');await runNode('scripts/bootstrap-channel-brand.mjs',[candidateId?`--candidate-id=${candidateId}`:`--channel-id=${channelId}`]);return{};}
  if(job.kind==='bootstrap_series'){const candidateId=String(payload.candidateId??'').trim();if(!candidateId)throw new Error('bootstrap_series requires candidateId');await runNode('scripts/bootstrap-series.mjs',[`--candidate-id=${candidateId}`]);await runNode('scripts/series-automation-profile-sync.mjs',[]);return{seriesCandidateId:candidateId};}
  if(job.kind==='analytics_sync'){const scoped=channelEnv(payload),channelId=String(payload.channelId??job.channel_id??'').trim();if(!channelId)throw new Error('analytics_sync requires a channelId');const days=Number(payload.days??28);await runNode('scripts/analytics-sync-channel.mjs',[`--days=${days}`,`--channel-id=${channelId}`],scoped);await runNode('scripts/economics-sync.mjs',[],scoped);await runNode('scripts/creative-learning-sync.mjs',[`--days=${Math.max(days,180)}`,`--channel-id=${channelId}`],scoped);return{};}
  if(job.kind==='market_cycle'){const args=[];if(payload.niche)args.push(`--niche=${String(payload.niche)}`);if(payload.maxQueries)args.push(`--max-queries=${Math.max(1,Math.floor(Number(payload.maxQueries)))}`);if(payload.days)args.push(`--days=${Math.max(1,Math.floor(Number(payload.days)))}`);await runNode('scripts/market-cycle.mjs',args);await runNode('scripts/market-pattern-sync.mjs',[`--niche=${String(payload.niche??process.env.PRIMARY_CHANNEL_KEY??'future-tech-business-en')}`,`--days=${Math.max(7,Math.floor(Number(payload.days??14)))}`]);return{};}
  if(job.kind==='schedule_publication'){const publicationId=String(payload.publicationId??'').trim(),publishAt=String(payload.publishAt??'').trim();if(!publicationId||!publishAt)throw new Error('schedule_publication job missing publicationId or publishAt');await runNode('scripts/schedule-publication.mjs',[`--publication-id=${publicationId}`,`--publish-at=${publishAt}`],channelEnv(payload));return{platform:'youtube',distributionState:'scheduled'};}
  if(job.kind==='distribute_publication'){
    const publicationId=String(payload.publicationId??'').trim(),platform=String(payload.platform??'').toLowerCase();if(!publicationId||!['youtube','tiktok','instagram','facebook'].includes(platform))throw new Error('distribute_publication requires publicationId and supported platform');
    await runNode('scripts/distribute-publication.mjs',[`--publication-id=${publicationId}`,`--platform=${platform}`],channelEnv(payload));
    const row=(await db.query(`select state,external_id,last_error,attempts from distribution_attempts where publication_id=$1 and platform=$2`,[publicationId,platform])).rows[0]??null,pollJobId=await scheduleDistributionPoll(job,row);
    return{platform,distributionState:row?.state??'unknown',externalId:row?.external_id??null,pollJobId};
  }
  if(job.kind==='apply_channel_brand'){const channelId=String(payload.channelId??job.channel_id??'').trim();if(!channelId)throw new Error('apply_channel_brand requires channelId');await runNode('scripts/apply-channel-brand.mjs',[`--channel-id=${channelId}`],channelEnv(payload));return{};}
  throw new Error(`Unsupported job kind ${job.kind}`);
}
async function settleBudget(job,actualCostUsd,releaseOnly=false){const payload=job.payload??{},channelKey=String(payload.channelKey??'future-tech-business-en'),reserved=Math.max(0,Number(payload.reservedCostUsd??0));if(!reserved)return;const budgetDate=String(payload.budgetDate??new Date().toISOString().slice(0,10));await db.query(`update daily_budget_ledger set reserved_usd=greatest(0,reserved_usd-$3),actual_usd=actual_usd+$4,updated_at=now() where channel_key=$1 and spend_date=$2::date`,[channelKey,budgetDate,reserved,releaseOnly?0:Math.max(0,actualCostUsd)]);}
async function complete(job,result){const completion=await db.query(`update jobs set state='succeeded',locked_at=null,locked_by=null,lease_owner=null,lease_expires_at=null,heartbeat_at=now(),completed_at=now(),updated_at=now(),last_error=null where id=$1 and lease_owner=$2`,[job.id,workerId]);if(completion.rowCount===0)throw new Error('Production job lease lost before completion; result not committed.');await settleBudget(job,result.actualCostUsd??0,false);await emit(job.id,'succeeded',{workerId,attempt:job.attempts,actualCostUsd:result.actualCostUsd??0,contentFormat:result.contentFormat??job.payload?.contentFormat,contentArchetype:result.contentArchetype??job.payload?.contentArchetype?.archetype??null,productionRunId:result.productionRunId,costMeterSession:result.costMeterSession,brandContinuityRequired:result.brandContinuityRequired??false,brandVersion:result.brandVersion??null,seriesId:result.seriesId??job.payload?.seriesId??null,seriesKey:result.seriesKey??job.payload?.seriesKey??null,seriesEpisodeId:result.seriesEpisodeId??job.payload?.seriesEpisodeId??null,platform:result.platform??job.payload?.platform??null,distributionState:result.distributionState??null,pollJobId:result.pollJobId??null});}
async function fail(job,error){const message=(error instanceof Error?error.message:String(error)).slice(0,8000),distribution=job.kind==='distribute_publication'&&job.payload?.publicationId&&job.payload?.platform;const providerQuotaBlocked=/\b429\b|quota|rate.?limit|exceeded your current quota|invalid_credentials/i.test(message);if(!providerQuotaBlocked&&shouldRetry(Number(job.attempts),Number(job.max_attempts))){const delayMs=computeRetryDelayMs(Number(job.attempts),{baseDelayMs:num('JOB_RETRY_BASE_MS',60000),maxDelayMs:num('JOB_RETRY_MAX_MS',6*60*60_000),jitterRatio:0.15});await db.query(`update jobs set state='retry',locked_at=null,locked_by=null,lease_owner=null,lease_expires_at=null,heartbeat_at=now(),not_before=now()+($2::text || ' milliseconds')::interval,last_error=$3,updated_at=now() where id=$1 and lease_owner=$4`,[job.id,String(delayMs),message,workerId]);if(distribution)await db.query(`update distribution_attempts set state='retry',last_error=$3,updated_at=now() where publication_id=$1 and platform=$2`,[job.payload.publicationId,job.payload.platform,message]).catch(()=>{});await emit(job.id,'retry_scheduled',{workerId,attempt:job.attempts,delayMs,error:message,kind:job.kind,contentFormat:job.payload?.contentFormat,contentArchetype:job.payload?.contentArchetype?.archetype??null,platform:job.payload?.platform??null});}else{await db.query(`update jobs set state='dead',locked_at=null,locked_by=null,lease_owner=null,lease_expires_at=null,heartbeat_at=now(),completed_at=now(),last_error=$2,updated_at=now() where id=$1 and lease_owner=$3`,[job.id,message,workerId]);await settleBudget(job,0,true);if(distribution)await db.query(`update distribution_attempts set state='failed',last_error=$3,updated_at=now() where publication_id=$1 and platform=$2`,[job.payload.publicationId,job.payload.platform,message]).catch(()=>{});if(job.payload?.seriesEpisodeId)await db.query(`update series_episodes set status='failed',updated_at=now() where id=$1`,[job.payload.seriesEpisodeId]).catch(()=>{});await emit(job.id,'dead_letter',{workerId,attempt:job.attempts,error:message,kind:job.kind,contentFormat:job.payload?.contentFormat,contentArchetype:job.payload?.contentArchetype?.archetype??null,seriesEpisodeId:job.payload?.seriesEpisodeId??null,platform:job.payload?.platform??null});}}
async function heartbeatJobLease(job){const result=await db.query(`update jobs set lease_expires_at=now()+($3::text||' milliseconds')::interval,heartbeat_at=now(),updated_at=now() where id=$1 and state='running' and lease_owner=$2`,[job.id,workerId,String(leaseMs)]);if(result.rowCount===0)throw new Error('Production job lease lost; refusing to continue execution.');}
async function executeWithHeartbeat(job){const meta=()=>({processed,jobId:job.id,kind:job.kind,attempt:job.attempts,channelId:job.channel_id??null,contentFormat:job.payload?.contentFormat??null,contentArchetype:job.payload?.contentArchetype?.archetype??null,seriesKey:job.payload?.seriesKey??null,episodeKey:job.payload?.seriesContext?.episodeKey??null,platform:job.payload?.platform??null});await heartbeatJobLease(job);await heartbeat('running',meta(),true);const timer=setInterval(()=>{Promise.all([heartbeatJobLease(job),heartbeat('running',meta())]).catch((error)=>console.error('heartbeat failed',error));},10_000);timer.unref?.();try{return await execute(job);}finally{clearInterval(timer);}}
try{await heartbeat('starting',{pollMs,staleMinutes,timeoutMinutes,once},true);const recovered=await recoverStale();if(recovered)console.log(`Recovered ${recovered} stale jobs`);await heartbeat('idle',{processed,recovered,pollMs},true);while(!stopping&&processed<maxJobs){await heartbeat('idle',{processed,pollMs});const job=await claim();if(!job){if(once)break;await sleep(pollMs);continue;}activeJob=job;try{const result=await executeWithHeartbeat(job);if(!stopping){await complete(job,result);processed+=1;await heartbeat('idle',{processed,lastJobId:job.id,lastJobKind:job.kind,lastResult:'succeeded'},true);}}catch(error){if(!stopping){await fail(job,error);processed+=1;await heartbeat('degraded',{processed,lastJobId:job.id,lastJobKind:job.kind,lastResult:'failed',error:error instanceof Error?error.message:String(error)},true);}}finally{if(activeJob?.id===job.id)activeJob=null;}if(once)break;}await heartbeat('stopping',{processed,stopping},true);}finally{await shutdownRequeuePromise;await db.close();}
console.log(JSON.stringify({workerId,processed,stopping},null,2));
