import Link from 'next/link';
import { notFound } from 'next/navigation';
import { requireSession } from '../../../lib/auth';
import { loadPilotRun } from '../../../lib/pilot-data';

export const dynamic = 'force-dynamic';
const money = (value: unknown) => new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 2 }).format(Number(value || 0));
const stateClass = (value: unknown) => { const state = String(value || '').toLowerCase(); return state.includes('complete') || state.includes('pass') ? 'good' : state.includes('fail') || state.includes('block') ? 'bad' : state.includes('partial') || state.includes('running') ? 'warn' : 'info'; };
const label = (value: unknown) => String(value || '—').replaceAll('_', ' ');

export default async function ProductionPilotPage({ params }: { params: Promise<{ id: string }> }) {
  await requireSession();
  const { id } = await params;
  const item = await loadPilotRun(id); if (!item) notFound();
  const { run, subtasks, artifacts, providerCalls, costEntries, qualityGates, reports } = item;
  const finalArtifact = artifacts.find((artifact: any) => artifact.artifactId === 'final-video');
  const captionArtifact = artifacts.find((artifact: any) => artifact.type === 'CAPTION');
  const audio = reports.AudioQualityReport;
  const visual = reports.VisualQualityReport;
  const review = reports.PilotReviewReport;
  const cost = reports.ProductionCostReport;
  const performance = reports.ProductionPerformanceReport;
  const visualPlan = reports.VisualStrategyPlan;
  const semantic = reports.SemanticSceneReport;
  const revision = reports.RevisionDecision;
  const thumbnails = reports.ThumbnailContactSheet;
  return <div className="content"><header className="topbar"><div><p className="eyebrow">Production review</p><h1>{id}</h1></div><Link href="/production-pilots" className="pill info">← Pilot runs</Link></header><main className="main">
    <section className="section card"><div className="row"><div><p className="eyebrow">Durable production run</p><h2>{label(run.format)} · {label(run.mode)}</h2><div className="fine">{run.videoId} · {run.channelId}</div></div><span className={`pill ${stateClass(run.status)}`}>{run.status}</span></div><div className="metric-grid detail-metrics" style={{ marginTop: 16 }}><div className="metric"><div className="label">Stage</div><div className="value">{label(run.currentStage)}</div></div><div className="metric"><div className="label">Budget</div><div className="value">{money(run.budget)}</div></div><div className="metric"><div className="label">Estimated</div><div className="value">{money(run.estimatedCost)}</div></div><div className="metric"><div className="label">Actual</div><div className="value">{money(run.actualCost)}</div></div><div className="metric"><div className="label">Resume from</div><div className="value">{label(run.resumeFrom)}</div></div><div className="metric"><div className="label">Provider calls</div><div className="value">{providerCalls.length}</div></div></div>{run.failureReason ? <div className="error" style={{ marginTop: 14 }}>Bloqueo: {run.failureStage} · {run.failureReason}</div> : null}<div className="button-row"><form action={`/api/production-pilots/${id}`} method="post"><button className="secondary" name="action" value="cancel" type="submit">Cancel run</button></form><span className="fine">Resume y retry se ejecutan desde el runner durable para conservar su executor y snapshot.</span></div></section>
    {finalArtifact ? <section className="section card"><div className="section-head"><div><p className="eyebrow">Final render</p><h2>final-video.mp4</h2></div><span className="pill good">REAL · LOCAL</span></div><video controls preload="metadata" src={`/api/production-pilots/${id}/artifacts/${finalArtifact.artifactId}`} style={{ width: '100%', borderRadius: 14, background: '#111' }} /><div className="fine" style={{ marginTop: 10 }}>{finalArtifact.mimeType} · {Math.round(finalArtifact.size / 1024)} KB · hash {finalArtifact.hash.slice(0, 12)}…</div></section> : null}
    <section className="section split"><div className="card"><div className="section-head"><div><p className="eyebrow">Scene execution</p><h2>Subtasks</h2></div><span className="fine">{subtasks.filter((task: any) => task.status === 'COMPLETE').length}/{subtasks.length} completas</span></div><div className="table-wrap"><table><thead><tr><th>Task</th><th>Provider</th><th>Status</th><th>Attempts</th><th>Cost</th><th>Artifact</th></tr></thead><tbody>{subtasks.map((task: any) => <tr key={task.taskKey}><td><strong>{task.taskKey}</strong><div className="fine">{task.kind}{task.sceneId ? ` · ${task.sceneId}` : ''}</div></td><td>{task.provider || task.fallbackStrategy?.preferred || 'LOCAL/FALLBACK'}</td><td><span className={`pill ${stateClass(task.status)}`}>{task.metadata?.cacheHit ? 'CACHED' : label(task.status)}</span></td><td>{task.attempt}</td><td>{money(task.actualCost)}</td><td>{task.artifactId ? <span className="pill good">REAL</span> : task.failureReason ? <span className="pill bad">FAILED</span> : <span className="pill info">—</span>}</td></tr>)}</tbody></table></div></div><div className="card"><p className="eyebrow">Artifacts</p><h2>Store local</h2><div className="list">{artifacts.map((artifact: any) => <div className="list-item" key={artifact.artifactId}><div><strong>{artifact.type}</strong><div className="fine">{artifact.provider} · {Math.round(artifact.size / 1024)} KB</div></div><a className="run-link" href={`/api/production-pilots/${id}/artifacts/${artifact.artifactId}`}>Abrir</a></div>)}</div>{captionArtifact ? <div className="fine" style={{ marginTop: 10 }}>Captions: <a className="run-link" href={`/api/production-pilots/${id}/artifacts/${captionArtifact.artifactId}`}>SRT</a></div> : null}</div></section>
    <section className="section split"><div className="card"><p className="eyebrow">Quality gates</p><h2>Readiness / QC</h2><div className="list">{qualityGates.map((gate: any) => <div className="list-item" key={gate.gateId}><span>{label(gate.gateId)}</span><span className={`pill ${stateClass(gate.status)}`}>{gate.status}</span></div>)}{!qualityGates.length ? <div className="empty">Los gates detallados están en los reports del runner.</div> : null}</div>{review?.blockers?.length ? <div className="error" style={{ marginTop: 12 }}>{review.blockers.map((blocker: string) => <div key={blocker}>• {blocker}</div>)}</div> : null}</div><div className="card"><p className="eyebrow">Pilot review</p><h2>{review?.status || 'NOT_EVALUATED'}</h2><div className="list">{Object.entries(review?.dimensions || {}).map(([name, value]: any) => <div className="list-item" key={name}><span>{name}</span><span className={`pill ${stateClass(value.status)}`}>{value.status}</span></div>)}</div></div></section>
    <section className="section split"><div className="card"><p className="eyebrow">Audio / visual</p><h2>Quality reports</h2><div className="code-box">{JSON.stringify({ audio, visual, semantic, revision }, null, 2)}</div></div><div className="card"><p className="eyebrow">Cost / performance</p><h2>Ledger</h2><div className="code-box">{JSON.stringify({ cost, performance, costEntries }, null, 2)}</div></div></section>
    <section className="section split"><div className="card"><p className="eyebrow">Visual plan</p><h2>Importance · strategy · fallback</h2><div className="list">{(visualPlan?.scenes || []).map((scene: any) => <div className="list-item" key={scene.sceneId}><span><strong>{scene.sceneId}</strong><div className="fine">{scene.importance?.class} · {scene.preferredStrategy}</div></span><span className="pill info">{scene.selectedProvider || 'LOCAL'}</span></div>)}</div></div><div className="card"><p className="eyebrow">Packaging</p><h2>Thumbnail contact sheet</h2>{thumbnails?.artifactId ? <a className="run-link" href={`/api/production-pilots/${id}/artifacts/${thumbnails.artifactId}`}>Abrir contact sheet ({thumbnails.candidates} opciones)</a> : <div className="fine">No hay contact sheet persistido.</div>}<div className="fine" style={{ marginTop: 12 }}>Semantic QC: <span className="pill warn">{semantic?.evaluationStatus || 'NOT_EVALUATED'}</span></div></div></section>
  </main></div>;
}
