import { createHash } from 'node:crypto';
import { mkdir, readFile, rename, writeFile } from 'node:fs/promises';
import { dirname, join, resolve } from 'node:path';
import type { ArtifactMetadata, ArtifactStore } from './artifact-store.js';
import type { SqlClient } from './sql.js';

export type DurableRunMode = 'DRY_RUN' | 'DRAFT' | 'FINAL';
export type DurableRunStatus = 'PLANNED' | 'READY' | 'RUNNING' | 'PARTIAL' | 'FAILED' | 'COMPLETED' | 'BLOCKED' | 'CANCELLED';
export type DurableTaskStatus = 'PENDING' | 'RUNNING' | 'COMPLETE' | 'FAILED' | 'BLOCKED' | 'CANCELLED';
export type DurableStage = 'PLANNING' | 'SCRIPT' | 'VOICE' | 'VISUALS' | 'AUDIO' | 'CAPTIONS' | 'RENDER' | 'QC' | 'REPORT';
export type DurableProductionRun = { id: string; videoId: string; channelId: string; format: string; mode: DurableRunMode; status: DurableRunStatus; createdAt: string; updatedAt: string; startedAt?: string; completedAt?: string; budget: number; estimatedCost: number; actualCost: number; currency: string; currentStage?: DurableStage; failureStage?: DurableStage; failureReason?: string; resumeFrom?: string; configSnapshot: Record<string, unknown> };
export type DurableProductionSubtask = { id: string; runId: string; taskKey: string; kind: string; sceneId?: string; dependencies: string[]; provider?: string; model?: string; inputHash: string; configHash: string; artifactHash?: string; artifactId?: string; attempt: number; status: DurableTaskStatus; estimatedCost: number; actualCost: number; fallbackStrategy?: Record<string, unknown>; failureReason?: string; metadata?: Record<string, unknown>; startedAt?: string; completedAt?: string; updatedAt: string };
export type ProviderCallRecord = { id: string; runId: string; subtaskId?: string; provider: string; model?: string; capability: string; status: string; requestHash?: string; providerRequestId?: string; providerJobId?: string; submittedAt?: string; completedAt?: string; responseStatus?: string; artifactId?: string; responseMetadata?: Record<string, unknown>; latencyMs?: number; cost: number; error?: string; createdAt: string };
export type CostEntryRecord = { id: string; runId: string; subtaskId?: string; category: string; provider?: string; operation: string; estimated: number; actual: number; currency: string; metadata?: Record<string, unknown>; createdAt: string };
export type QualityGateRecord = { id: string; runId: string; gateId: string; status: string; message: string; critical: boolean; payload?: Record<string, unknown>; createdAt: string };
export type DurableRunSnapshot = { run: DurableProductionRun; subtasks: DurableProductionSubtask[]; artifacts: ArtifactMetadata[]; providerCalls: ProviderCallRecord[]; costEntries: CostEntryRecord[]; qualityGates: QualityGateRecord[]; reports: Record<string, unknown> };
export type DurableTaskResult = { artifact?: ArtifactMetadata; actualCost?: number; providerCall?: Omit<ProviderCallRecord, 'id' | 'runId' | 'subtaskId' | 'createdAt'>; costEntry?: Omit<CostEntryRecord, 'id' | 'runId' | 'subtaskId' | 'createdAt'> };
export type DurableTaskExecutor = (task: DurableProductionSubtask, snapshot: DurableRunSnapshot) => Promise<DurableTaskResult>;

const id = (prefix: string) => `${prefix}-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
const hash = (value: unknown) => createHash('sha256').update(JSON.stringify(value)).digest('hex');
async function atomic(path: string, value: unknown) { await mkdir(dirname(path), { recursive: true }); const temp = `${path}.${process.pid}.tmp`; await writeFile(temp, `${JSON.stringify(value, null, 2)}\n`, 'utf8'); await rename(temp, path); }

export class FileDurableProductionStore {
  readonly root: string;
  constructor(root = '.data/production-runs') { this.root = resolve(root); }
  private dir(runId: string) { return join(this.root, runId); }
  private file(runId: string, name: string) { return join(this.dir(runId), `${name}.json`); }
  async createRun(input: Omit<DurableProductionRun, 'createdAt' | 'updatedAt'> & Partial<Pick<DurableProductionRun, 'createdAt' | 'updatedAt'>>) { const now = new Date().toISOString(); const run = { ...input, createdAt: input.createdAt ?? now, updatedAt: input.updatedAt ?? now }; await atomic(this.file(run.id, 'run'), run); for (const name of ['subtasks', 'provider-calls', 'cost-entries', 'quality-gates', 'reports']) await atomic(this.file(run.id, name), name === 'reports' ? {} : []); return run; }
  async load(runId: string): Promise<DurableRunSnapshot | null> { try { const run = JSON.parse(await readFile(this.file(runId, 'run'), 'utf8')) as DurableProductionRun; const read = async <T>(name: string, fallback: T) => { try { return JSON.parse(await readFile(this.file(runId, name), 'utf8')) as T; } catch { return fallback; } }; return { run, subtasks: await read('subtasks', []), artifacts: [], providerCalls: await read('provider-calls', []), costEntries: await read('cost-entries', []), qualityGates: await read('quality-gates', []), reports: await read('reports', {}) }; } catch { return null; } }
  async saveRun(run: DurableProductionRun) { await atomic(this.file(run.id, 'run'), { ...run, updatedAt: new Date().toISOString() }); }
  async saveSubtasks(runId: string, tasks: DurableProductionSubtask[]) { await atomic(this.file(runId, 'subtasks'), tasks); }
  async saveProviderCalls(runId: string, values: ProviderCallRecord[]) { await atomic(this.file(runId, 'provider-calls'), values); }
  async saveCostEntries(runId: string, values: CostEntryRecord[]) { await atomic(this.file(runId, 'cost-entries'), values); }
  async saveQualityGates(runId: string, values: QualityGateRecord[]) { await atomic(this.file(runId, 'quality-gates'), values); }
  async saveReport(runId: string, type: string, value: unknown) { const snapshot = await this.load(runId); if (!snapshot) throw new Error(`Unknown durable run ${runId}`); await atomic(this.file(runId, 'reports'), { ...snapshot.reports, [type]: value }); }
}

export function makeDurableRun(input: { id: string; videoId: string; channelId: string; format: string; mode: DurableRunMode; budget: number; estimatedCost: number; configSnapshot: Record<string, unknown> }): DurableProductionRun { const now = new Date().toISOString(); return { ...input, status: input.mode === 'DRY_RUN' ? 'COMPLETED' : 'PLANNED', actualCost: 0, currency: 'USD', createdAt: now, updatedAt: now }; }
export function makeDurableTask(input: Omit<DurableProductionSubtask, 'id' | 'attempt' | 'status' | 'actualCost' | 'updatedAt'>): DurableProductionSubtask { return { ...input, id: id('task'), attempt: 0, status: 'PENDING', actualCost: 0, updatedAt: new Date().toISOString() }; }

export async function resumeProductionRun(runId: string, store: FileDurableProductionStore, artifacts: ArtifactStore, execute: DurableTaskExecutor): Promise<DurableRunSnapshot> {
  const snapshot = await store.load(runId); if (!snapshot) throw new Error(`Unknown durable run ${runId}`);
  const tasks = snapshot.subtasks.map((task) => ({ ...task, metadata: { ...(task.metadata ?? {}) } }));
  for (const task of tasks) {
    if (task.status === 'COMPLETE' && task.artifactId) { const artifact = await artifacts.get(task.artifactId); if (artifact && await artifacts.isValid(artifact)) task.metadata!.cacheHit = true; else { task.status = 'PENDING'; task.artifactId = undefined; task.artifactHash = undefined; task.metadata!.cacheInvalidated = true; } }
    if (task.status === 'FAILED') { task.status = 'PENDING'; task.failureReason = undefined; }
  }
  snapshot.subtasks = tasks; snapshot.run.status = 'RUNNING'; snapshot.run.startedAt ??= new Date().toISOString(); await store.saveRun(snapshot.run); await store.saveSubtasks(runId, tasks);
  let progress = true;
  while (progress) {
    progress = false;
    for (const task of tasks) {
      if (task.status !== 'PENDING' || task.dependencies.some((dependency) => tasks.find((candidate) => candidate.taskKey === dependency)?.status !== 'COMPLETE')) continue;
      progress = true; task.status = 'RUNNING'; task.attempt += 1; task.startedAt = new Date().toISOString(); snapshot.run.currentStage = (task.kind as DurableStage); snapshot.run.resumeFrom = task.taskKey; await store.saveRun(snapshot.run); await store.saveSubtasks(runId, tasks);
      try {
        const result = await execute(task, { ...snapshot, subtasks: tasks }); task.status = 'COMPLETE'; task.completedAt = new Date().toISOString(); task.actualCost += Math.max(0, result.actualCost ?? 0); snapshot.run.actualCost += Math.max(0, result.actualCost ?? 0); if (result.artifact) { task.artifactId = result.artifact.artifactId; task.artifactHash = result.artifact.hash; snapshot.artifacts.push(result.artifact); } if (result.providerCall) snapshot.providerCalls.push({ ...result.providerCall, id: id('provider-call'), runId, subtaskId: task.id, createdAt: new Date().toISOString() }); if (result.costEntry) snapshot.costEntries.push({ ...result.costEntry, id: id('cost'), runId, subtaskId: task.id, createdAt: new Date().toISOString() });
      } catch (error) { task.status = 'FAILED'; task.failureReason = error instanceof Error ? error.message : String(error); snapshot.run.failureStage = task.kind as DurableStage; snapshot.run.failureReason = task.failureReason; }
      task.updatedAt = new Date().toISOString(); await store.saveRun(snapshot.run); await store.saveSubtasks(runId, tasks); await store.saveProviderCalls(runId, snapshot.providerCalls); await store.saveCostEntries(runId, snapshot.costEntries); if (task.status === 'FAILED') break;
    }
    if (tasks.some((task) => task.status === 'FAILED')) break;
  }
  const failed = tasks.find((task) => task.status === 'FAILED'); const blocked = tasks.find((task) => task.status === 'PENDING' && task.dependencies.some((dependency) => tasks.find((candidate) => candidate.taskKey === dependency)?.status !== 'COMPLETE')); const complete = tasks.every((task) => task.status === 'COMPLETE'); snapshot.run.status = failed ? 'PARTIAL' : complete ? 'COMPLETED' : blocked ? 'BLOCKED' : 'PARTIAL'; snapshot.run.resumeFrom = tasks.find((task) => task.status !== 'COMPLETE')?.taskKey; if (complete) snapshot.run.completedAt = new Date().toISOString(); await store.saveRun(snapshot.run); await store.saveSubtasks(runId, tasks); return { ...snapshot, run: snapshot.run, subtasks: tasks };
}

export class DurableProductionRepository {
  constructor(private readonly db: SqlClient) {}
  async createRun(input: { id?: string; videoId: string; channelId: string; contentIdeaId?: string; format: string; mode: DurableRunMode; budget: number; estimatedCost: number; configSnapshot: unknown }) { const r = await this.db.query<{ id: string }>(`insert into production_runs (id,content_idea_id,video_id,channel_id,format,mode,status,state,budget_usd,estimated_cost_usd,actual_cost_usd,total_cost_usd,config_snapshot,metadata) values (coalesce($1::uuid,gen_random_uuid()),$2,$3,$4,$5,$6,'PLANNED','PLANNED',$7,$8,0,0,$9::jsonb,$9::jsonb) returning id`, [input.id ?? null, input.contentIdeaId ?? null, input.videoId, input.channelId, input.format, input.mode, input.budget, input.estimatedCost, JSON.stringify(input.configSnapshot)]); if (!r.rows[0]) throw new Error('Durable production run insert returned no row'); return r.rows[0].id; }
  async updateRun(id: string, input: Partial<Pick<DurableProductionRun, 'status' | 'startedAt' | 'completedAt' | 'actualCost' | 'currentStage' | 'failureStage' | 'failureReason' | 'resumeFrom'>> & { configSnapshot?: unknown }) { await this.db.query(`update production_runs set status=coalesce($2,status),state=coalesce($2,state),started_at=coalesce($3,started_at),completed_at=coalesce($4,completed_at),actual_cost_usd=coalesce($5,actual_cost_usd),total_cost_usd=coalesce($5,total_cost_usd),current_stage=coalesce($6,current_stage),failure_stage=coalesce($7,failure_stage),failure_reason=coalesce($8,failure_reason),resume_from=coalesce($9,resume_from),config_snapshot=coalesce($10::jsonb,config_snapshot),updated_at=now() where id=$1`, [id, input.status ?? null, input.startedAt ?? null, input.completedAt ?? null, input.actualCost ?? null, input.currentStage ?? null, input.failureStage ?? null, input.failureReason ?? null, input.resumeFrom ?? null, input.configSnapshot === undefined ? null : JSON.stringify(input.configSnapshot)]); }
  async upsertSubtask(input: Omit<DurableProductionSubtask, 'id'> & { id?: string }) { const r = await this.db.query<{ id: string }>(`insert into production_subtasks (id,production_run_id,task_key,kind,scene_id,dependencies,provider,model,input_hash,config_hash,artifact_hash,artifact_id,attempt,status,estimated_cost_usd,actual_cost_usd,fallback_strategy,failure_reason,metadata,started_at,completed_at,updated_at) values (coalesce($1::uuid,gen_random_uuid()),$2,$3,$4,$5,$6::jsonb,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17::jsonb,$18,$19::jsonb,$20,$21,$22) on conflict (production_run_id,task_key) do update set status=excluded.status,artifact_hash=excluded.artifact_hash,artifact_id=excluded.artifact_id,attempt=excluded.attempt,actual_cost_usd=excluded.actual_cost_usd,failure_reason=excluded.failure_reason,metadata=excluded.metadata,started_at=excluded.started_at,completed_at=excluded.completed_at,updated_at=now() returning id`, [input.id ?? null, input.runId, input.taskKey, input.kind, input.sceneId ?? null, JSON.stringify(input.dependencies), input.provider ?? null, input.model ?? null, input.inputHash, input.configHash, input.artifactHash ?? null, input.artifactId ?? null, input.attempt, input.status, input.estimatedCost, input.actualCost, JSON.stringify(input.fallbackStrategy ?? {}), input.failureReason ?? null, JSON.stringify(input.metadata ?? {}), input.startedAt ?? null, input.completedAt ?? null, input.updatedAt]); if (!r.rows[0]) throw new Error('Durable subtask upsert returned no row'); return r.rows[0].id; }
  async addArtifact(input: ArtifactMetadata) { await this.db.query(`insert into generated_artifacts (id,production_run_id,scene_id,type,mime_type,provider,model,storage_key,local_path,size_bytes,duration_seconds,resolution,content_hash,cost_usd,is_draft,is_final,metadata) values ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12::jsonb,$13,$14,$15,$16,$17::jsonb) on conflict (production_run_id,content_hash) do nothing`, [input.artifactId, input.runId, input.sceneId ?? null, input.type, input.mimeType, input.provider, input.model ?? null, input.storageKey, input.path, input.size, input.duration ?? null, JSON.stringify(input.resolution ?? null), input.hash, input.cost, input.isDraft, input.isFinal, JSON.stringify(input.metadata ?? {})]); }
  async addProviderCall(input: ProviderCallRecord) { await this.db.query(`insert into provider_calls (id,production_run_id,subtask_id,provider,model,capability,status,request_hash,provider_request_id,provider_job_id,submitted_at,completed_at,response_status,artifact_id,response_metadata,latency_ms,cost_usd,error) values ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15::jsonb,$16,$17,$18)`, [input.id, input.runId, input.subtaskId ?? null, input.provider, input.model ?? null, input.capability, input.status, input.requestHash ?? null, input.providerRequestId ?? null, input.providerJobId ?? null, input.submittedAt ?? null, input.completedAt ?? null, input.responseStatus ?? null, input.artifactId ?? null, JSON.stringify(input.responseMetadata ?? {}), input.latencyMs ?? null, input.cost, input.error ?? null]); }
  async findProviderReceipt(runId: string, requestHash: string) { const result = await this.db.query<ProviderCallRecord>(`select id,production_run_id as "runId",subtask_id as "subtaskId",provider,model,capability,status,request_hash as "requestHash",provider_request_id as "providerRequestId",provider_job_id as "providerJobId",submitted_at as "submittedAt",completed_at as "completedAt",response_status as "responseStatus",artifact_id as "artifactId",response_metadata as "responseMetadata",latency_ms as "latencyMs",cost_usd as cost,error,created_at as "createdAt" from provider_calls where production_run_id=$1 and request_hash=$2 order by created_at desc limit 1`, [runId, requestHash]); return result.rows[0] ?? null; }
  async addCostEntry(input: CostEntryRecord) { await this.db.query(`insert into production_cost_entries (id,production_run_id,subtask_id,category,provider,operation,estimated_usd,actual_usd,currency,metadata) values ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10::jsonb)`, [input.id, input.runId, input.subtaskId ?? null, input.category, input.provider ?? null, input.operation, input.estimated, input.actual, input.currency, JSON.stringify(input.metadata ?? {})]); }
  async saveGate(input: QualityGateRecord) { await this.db.query(`insert into production_quality_gates (id,production_run_id,gate_id,status,message,critical,payload) values ($1,$2,$3,$4,$5,$6,$7::jsonb) on conflict (production_run_id,gate_id) do update set status=excluded.status,message=excluded.message,critical=excluded.critical,payload=excluded.payload`, [input.id, input.runId, input.gateId, input.status, input.message, input.critical, JSON.stringify(input.payload ?? {})]); }
  async saveReport(runId: string, reportType: string, payload: unknown) { await this.db.query(`insert into production_reports (production_run_id,report_type,payload) values ($1,$2,$3::jsonb) on conflict (production_run_id,report_type) do update set payload=excluded.payload,created_at=now()`, [runId, reportType, JSON.stringify(payload)]); }
}

export const durableInputHash = hash;
