export type ReportStatus = 'PASS' | 'WARN' | 'FAIL' | 'NOT_EVALUATED';
export type AudioQualityReport = { status: ReportStatus; voice: { present: boolean; durationSeconds: number; normalized: boolean }; music: { present: boolean; ducking: boolean }; sfx: { count: number; present: boolean }; clippingProxy: number; silenceSeconds: number; issues: string[] };
export type VisualQualityReport = { status: ReportStatus; checkedScenes: number; missingArtifacts: string[]; wrongResolution: string[]; wrongAspectRatio: string[]; blackFrameSeconds: number; corruptArtifacts: string[]; excessiveStillScenes: string[]; tooShortScenes: string[]; timelineGaps: number; duplicateAssets: string[]; invalidDurations: string[]; semanticEvaluation: ReportStatus; issues: string[] };
export type ProductionCostReport = { currency: string; byCategory: Record<string, { estimated: number; actual: number; delta: number }>; estimatedTotal: number; actualTotal: number; delta: number; costPerSecond: number; costPerScene: number };
export type ProductionPerformanceReport = { startedAt?: string; completedAt?: string; totalWallClockMs: number; stages: Array<{ stage: string; durationMs: number; status: string }>; providerLatencyMs: Record<string, number>; generationRetries: number; cacheHits: number; cacheSavings: number };
export type PilotReviewReport = { status: 'PASS' | 'PARTIALLY_EXECUTABLE' | 'BLOCKED'; dimensions: Record<string, { status: ReportStatus; evidence?: string }>; blockers: string[] };

export function buildAudioQualityReport(input: Omit<AudioQualityReport, 'status'>): AudioQualityReport { const issues = [...input.issues]; if (!input.voice.present) issues.push('voice-missing'); if (input.clippingProxy > 0) issues.push('audio-clipping-proxy'); const status: ReportStatus = issues.length ? 'FAIL' : 'PASS'; return { ...input, issues, status }; }
export function buildVisualQualityReport(input: Omit<VisualQualityReport, 'status'>): VisualQualityReport { const issues = [...input.issues, ...input.missingArtifacts.map((id) => `${id}:missing`), ...input.corruptArtifacts.map((id) => `${id}:corrupt`), ...input.invalidDurations.map((id) => `${id}:invalid-duration`)]; const status: ReportStatus = issues.length ? 'FAIL' : input.semanticEvaluation === 'NOT_EVALUATED' ? 'WARN' : 'PASS'; return { ...input, issues, status }; }
export function buildProductionCostReport(input: { entries: Array<{ category: string; estimated: number; actual: number }>; durationSeconds: number; sceneCount: number; currency?: string }): ProductionCostReport { const byCategory: ProductionCostReport['byCategory'] = {}; for (const entry of input.entries) { const bucket = byCategory[entry.category] ?? { estimated: 0, actual: 0, delta: 0 }; bucket.estimated += Math.max(0, entry.estimated); bucket.actual += Math.max(0, entry.actual); bucket.delta = bucket.actual - bucket.estimated; byCategory[entry.category] = bucket; } const estimatedTotal = Object.values(byCategory).reduce((sum, value) => sum + value.estimated, 0); const actualTotal = Object.values(byCategory).reduce((sum, value) => sum + value.actual, 0); return { currency: input.currency ?? 'USD', byCategory, estimatedTotal, actualTotal, delta: actualTotal - estimatedTotal, costPerSecond: actualTotal / Math.max(0.1, input.durationSeconds), costPerScene: actualTotal / Math.max(1, input.sceneCount) }; }
export function buildPerformanceReport(input: { startedAt?: string; completedAt?: string; stages: Array<{ stage: string; startedAt: string; completedAt: string; status: string }>; providerLatencyMs?: Record<string, number>; generationRetries?: number; cacheHits?: number; cacheSavings?: number }): ProductionPerformanceReport { const totalWallClockMs = input.startedAt && input.completedAt ? Math.max(0, new Date(input.completedAt).getTime() - new Date(input.startedAt).getTime()) : input.stages.reduce((sum, item) => sum + Math.max(0, new Date(item.completedAt).getTime() - new Date(item.startedAt).getTime()), 0); return { startedAt: input.startedAt, completedAt: input.completedAt, totalWallClockMs, stages: input.stages.map((item) => ({ stage: item.stage, durationMs: Math.max(0, new Date(item.completedAt).getTime() - new Date(item.startedAt).getTime()), status: item.status })), providerLatencyMs: input.providerLatencyMs ?? {}, generationRetries: input.generationRetries ?? 0, cacheHits: input.cacheHits ?? 0, cacheSavings: input.cacheSavings ?? 0 }; }
